"""
adversarial_test_set.py
────────────────────────
100 hand-authored synthetic emails (NOT sampled from Enron) with ground-truth
category / priority / sentiment assigned at write time. Purpose: the trained
models have only ever been validated via cross-validation on 2001 Enron mail
(gold_priority_labeled.csv, gold_category set) — this checks whether they
generalize to modern phrasing, casual/texting style, sarcasm, and the known
failure modes already documented in PROJECT_STATUS.md (e.g. keyword-free
urgency, positive-sentiment-but-urgent, marketing hype using "URGENT" for a
sale).

Fields per email:
  id, subject, body, to, from_addr
  expected_category   -> 'Work' | 'Personal' | 'Other'  (matches cat classes)
  expected_priority    -> 'low' | 'medium' | 'high'
  expected_sentiment   -> 'positive' | 'neutral' | 'negative'  (informational —
                          not a final classify() output, checked against the
                          sign/magnitude of VADER compound as a diagnostic,
                          not scored as pass/fail against the pipeline)
  note                 -> what this case is specifically probing

Distribution (deliberately NOT matching the real-world skew — real mail is
~69% low/24% medium/7% high; this set over-samples "high" and known-tricky
cases on purpose, since the goal is stress-testing, not measuring the
production base rate):
  Work: 10 low, 10 medium, 10 high
  Personal: 10 low, 8 medium, 8 high
  Other: 12 low, 6 medium, 4 high
  Adversarial/mixed (block J): 22, spanning all three categories/priorities
"""

TEST_EMAILS = [
    # ── Block A: Work - low (routine, no action needed) ──────────────────
    dict(id="A1", subject="Weekly status report - Engineering",
         body="Attached is this week's status report. Sprint velocity was on target, no blockers to flag.",
         to="team-eng@company.com", from_addr="pm@company.com",
         expected_category="Work", expected_priority="low", expected_sentiment="neutral",
         note="routine report"),
    dict(id="A2", subject="FYI - coffee machine on 3rd floor fixed",
         body="Just a heads up the coffee machine is working again. No action needed.",
         to="floor3@company.com", from_addr="facilities@company.com",
         expected_category="Work", expected_priority="low", expected_sentiment="neutral",
         note="trivial FYI"),
    dict(id="A3", subject="Reminder: submit timesheet before end of month",
         body="Just a friendly reminder to log your hours before the month closes out. Plenty of time still.",
         to="staff@company.com", from_addr="hr@company.com",
         expected_category="Work", expected_priority="low", expected_sentiment="neutral",
         note="distant deadline, low pressure"),
    dict(id="A4", subject="Minutes from yesterday's team meeting",
         body="Sharing the notes from yesterday's sync for anyone who missed it. Nothing urgent in here.",
         to="team@company.com", from_addr="lead@company.com",
         expected_category="Work", expected_priority="low", expected_sentiment="neutral",
         note="routine notes"),
    dict(id="A5", subject="New parking policy starting next quarter",
         body="Heads up that the parking assignment policy is changing next quarter. Details attached for whenever you get a chance to look.",
         to="all-staff@company.com", from_addr="admin@company.com",
         expected_category="Work", expected_priority="low", expected_sentiment="neutral",
         note="future policy change"),
    dict(id="A6", subject="Congrats on the product launch!",
         body="Just wanted to say great work on shipping the new feature this week. No reply needed, just wanted to say it.",
         to="dev-team@company.com", from_addr="director@company.com",
         expected_category="Work", expected_priority="low", expected_sentiment="positive",
         note="positive tone but zero action needed"),
    dict(id="A7", subject="Quarterly newsletter from HR",
         body="This quarter's HR newsletter covers benefits updates and upcoming events. Read whenever convenient.",
         to="staff@company.com", from_addr="hr@company.com",
         expected_category="Work", expected_priority="low", expected_sentiment="neutral",
         note="internal newsletter"),
    dict(id="A8", subject="Server maintenance completed successfully last night",
         body="The scheduled maintenance finished without issues overnight. Everything is back to normal, no action needed on your end.",
         to="eng@company.com", from_addr="it@company.com",
         expected_category="Work", expected_priority="low", expected_sentiment="neutral",
         note="past-tense resolved issue"),
    dict(id="A9", subject="Work book club - sign up if interested",
         body="Starting a casual book club, first pick is a productivity book. Reply if you'd like to join, totally optional.",
         to="staff@company.com", from_addr="colleague@company.com",
         expected_category="Work", expected_priority="low", expected_sentiment="positive",
         note="optional social"),
    dict(id="A10", subject="Slide deck from last week's town hall",
         body="Attaching the deck from last week's town hall in case anyone wants to reference it later.",
         to="staff@company.com", from_addr="comms@company.com",
         expected_category="Work", expected_priority="low", expected_sentiment="neutral",
         note="archival share"),

    # ── Block B: Work - medium (needs a response, not an emergency) ──────
    dict(id="B1", subject="Please review the attached proposal this week",
         body="When you get a chance this week, could you take a look at the attached proposal and send thoughts?",
         to="colleague@company.com", from_addr="manager@company.com",
         expected_category="Work", expected_priority="medium", expected_sentiment="neutral",
         note="soft deadline, real ask"),
    dict(id="B2", subject="Reminder: self-assessment due Friday",
         body="Just a reminder your performance self-assessment is due this Friday. Should only take 20 minutes.",
         to="employee@company.com", from_addr="hr@company.com",
         expected_category="Work", expected_priority="medium", expected_sentiment="neutral",
         note="this-week deadline"),
    dict(id="B3", subject="Availability for a call next week?",
         body="Could you send over your availability for a 30 min call sometime next week? Want to sync on the roadmap.",
         to="peer@company.com", from_addr="colleague@company.com",
         expected_category="Work", expected_priority="medium", expected_sentiment="neutral",
         note="scheduling ask"),
    dict(id="B4", subject="Budget draft needs your feedback before Thursday",
         body="Attached the draft budget for next quarter. Could use your feedback before our Thursday meeting.",
         to="finance-lead@company.com", from_addr="manager@company.com",
         expected_category="Work", expected_priority="medium", expected_sentiment="neutral",
         note="concrete near deadline"),
    dict(id="B5", subject="Following up on my email from last week",
         body="Just following up in case this got buried - any update on the vendor contract question?",
         to="colleague@company.com", from_addr="manager@company.com",
         expected_category="Work", expected_priority="medium", expected_sentiment="neutral",
         note="polite follow-up nudge"),
    dict(id="B6", subject="PTO request for next month - need approval",
         body="Could you approve my PTO request for the second week of next month when you have a moment?",
         to="manager@company.com", from_addr="employee@company.com",
         expected_category="Work", expected_priority="medium", expected_sentiment="neutral",
         note="approval needed, not time-critical"),
    dict(id="B7", subject="Please complete onboarding checklist by Wednesday",
         body="Welcome to the team! Please complete the attached onboarding checklist by Wednesday so IT can finish setup.",
         to="newhire@company.com", from_addr="hr@company.com",
         expected_category="Work", expected_priority="medium", expected_sentiment="positive",
         note="onboarding task with real deadline"),
    dict(id="B8", subject="Client question on the contract - need your input",
         body="The client asked a question about section 4 of the contract. Can you weigh in before I respond to them?",
         to="legal@company.com", from_addr="account-manager@company.com",
         expected_category="Work", expected_priority="medium", expected_sentiment="neutral",
         note="blocking someone else, moderate stakes"),
    dict(id="B9", subject="Need your input on the marketing copy",
         body="We're finalizing the campaign copy soon and would love your input before we lock it in.",
         to="reviewer@company.com", from_addr="marketing@company.com",
         expected_category="Work", expected_priority="medium", expected_sentiment="neutral",
         note="soft close deadline"),
    dict(id="B10", subject="Your software license renews soon",
         body="Reminder that your license lapses next week - please renew it so you don't lose access.",
         to="employee@company.com", from_addr="it@company.com",
         expected_category="Work", expected_priority="medium", expected_sentiment="neutral",
         note="expiring-soon but not same-day"),

    # ── Block C: Work - high (real, immediate) ────────────────────────────
    dict(id="C1", subject="URGENT: Approval needed by EOD",
         body="Please sign off on the attached contract before end of day. Legal is waiting.",
         to="ceo@company.com", from_addr="legal@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="neutral",
         note="the known EOD-approval case from PROJECT_STATUS.md item 3c/3d — re-tested here"),
    dict(id="C2", subject="Site is down, customers can't check out",
         body="Checkout is throwing errors for every customer right now. Need eyes on this immediately.",
         to="oncall@company.com", from_addr="monitoring@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="negative",
         note="real outage"),
    dict(id="C3", subject="Legal filing deadline is tomorrow morning",
         body="We cannot miss the filing deadline tomorrow morning. I need the final documents from you tonight.",
         to="paralegal@company.com", from_addr="attorney@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="neutral",
         note="hard external deadline"),
    dict(id="C4", subject="Board meeting starts in an hour",
         body="It is imperative that this is fixed before the board meeting starts in an hour. No excuses.",
         to="finance-team@company.com", from_addr="cfo@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="negative",
         note="the original heuristic false-negative example from PROJECT_STATUS.md"),
    dict(id="C5", subject="Wire transfer sign-off needed before the bank closes",
         body="I need your sign-off on the wire transfer in the next hour, the bank closes at 5pm and this can't wait until tomorrow.",
         to="controller@company.com", from_addr="cfo@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="neutral",
         note="hard same-day cutoff, no keyword like 'urgent'"),
    dict(id="C6", subject="We lost our biggest client over this",
         body="We just lost our biggest client because of this issue. I need a call from you in the next 10 minutes.",
         to="account-lead@company.com", from_addr="vp-sales@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="negative",
         note="crisis, no urgency keyword"),
    dict(id="C7", subject="Don't leave yet",
         body="Don't leave yet, this can't wait until tomorrow, I need the final numbers from you before you go.",
         to="analyst@company.com", from_addr="manager@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="neutral",
         note="keyword-free urgency — no 'urgent/asap/emergency' etc"),
    dict(id="C8", subject="Auditors are here asking for Q3 statements",
         body="The auditors just arrived and are asking for the Q3 statements right now. Can you send them over immediately.",
         to="accounting@company.com", from_addr="controller@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="neutral",
         note="in-the-moment pressure"),
    dict(id="C9", subject="Production database corrupting records",
         body="We're seeing data corruption in production right now. Please call me the second you see this.",
         to="dba@company.com", from_addr="oncall@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="negative",
         note="technical crisis"),
    dict(id="C10", subject="Contract expires at midnight, still unsigned",
         body="The contract expires at midnight and legal hasn't signed off yet. Need this resolved immediately or we lose the deal.",
         to="legal@company.com", from_addr="deal-lead@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="negative",
         note="hard deadline same day"),

    # ── Block D: Personal - low ────────────────────────────────────────────
    dict(id="D1", subject="thought of you",
         body="Saw this today and thought of you, no need to reply, just wanted to share.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="low", expected_sentiment="positive",
         note="pure social, explicit no-reply-needed"),
    dict(id="D2", subject="vacation photos from last weekend",
         body="Finally uploaded the photos from the trip, here's the link whenever you want to look.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="low", expected_sentiment="positive",
         note="casual share"),
    dict(id="D3", subject="that recipe you asked about",
         body="Here's the recipe from last month, sorry it took a while to send over. No rush trying it.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="low", expected_sentiment="neutral",
         note="delayed but low-stakes favor"),
    dict(id="D4", subject="what are you up to this weekend",
         body="No big plans here, just wondering what you're up to this weekend, no rush to answer.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="low", expected_sentiment="neutral",
         note="casual check-in"),
    dict(id="D5", subject="found a book you'd like",
         body="Saw this at the store and it made me think of you, figured I'd mention it.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="low", expected_sentiment="positive",
         note="casual mention"),
    dict(id="D6", subject="remember that trip years ago?",
         body="Was going through old photos and found ones from that trip we took, made me laugh.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="low", expected_sentiment="positive",
         note="nostalgia, no ask"),
    dict(id="D7", subject="new address",
         body="Just moved, here's my new address in case you ever want to send something, no rush.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="low", expected_sentiment="neutral",
         note="FYI, no deadline"),
    dict(id="D8", subject="checking in",
         body="Hope you're doing well, just checking in, no need to respond right away.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="low", expected_sentiment="positive",
         note="explicit low-pressure check-in"),
    dict(id="D9", subject="playlist I mentioned",
         body="Here's that playlist from the other day, enjoy whenever.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="low", expected_sentiment="positive",
         note="casual share"),
    dict(id="D10", subject="lol look at this",
         body="Saw this meme and immediately thought of you, sending it your way, no reply needed lol.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="low", expected_sentiment="positive",
         note="pure fun, casual texting tone"),

    # ── Block E: Personal - medium ─────────────────────────────────────────
    dict(id="E1", subject="reschedule dinner?",
         body="Can we move dinner to next week instead? Let me know what days work for you.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="medium", expected_sentiment="neutral",
         note="real scheduling ask, not urgent"),
    dict(id="E2", subject="need your address for the wedding invite",
         body="We're sending out invites soon, can you send your current address when you get a chance?",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="medium", expected_sentiment="positive",
         note="real ask, mild deadline"),
    dict(id="E3", subject="thinking about visiting next month",
         body="I'm considering coming to visit next month, are you free that week? Let me know so I can book flights.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="medium", expected_sentiment="positive",
         note="planning ask with soft deadline (flight booking)"),
    dict(id="E4", subject="pick me up Saturday?",
         body="Would you be able to grab me from the airport Saturday afternoon? Let me know if that works for you.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="medium", expected_sentiment="neutral",
         note="concrete favor, needs an answer"),
    dict(id="E5", subject="mom's birthday coming up",
         body="Mom's birthday is in a couple weeks, want to plan something together? Let's figure it out soon.",
         to="sibling@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="medium", expected_sentiment="positive",
         note="coordination needed, has a real date"),
    dict(id="E6", subject="still interested in the apartment?",
         body="Following up on the apartment we talked about, are you still interested? The landlord wants an answer soon.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="medium", expected_sentiment="neutral",
         note="external soft deadline"),
    dict(id="E7", subject="that book I lent you",
         body="Whenever you get a chance, could you send back the book I lent you? Need it for a project sometime this week.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="medium", expected_sentiment="neutral",
         note="mild request with a soft this-week timeframe"),
    dict(id="E8", subject="holiday plans - when can we talk?",
         body="We should figure out the holiday plans soon, when are you free to hop on a call this week?",
         to="family@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="medium", expected_sentiment="neutral",
         note="coordination, mild time pressure"),

    # ── Block F: Personal - high (real emergencies) ─────────────────────────
    dict(id="F1", subject="call me now",
         body="Dad was just rushed to the hospital, please call me as soon as you get this.",
         to="sibling@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="high", expected_sentiment="negative",
         note="family medical emergency"),
    dict(id="F2", subject="flight cancelled, stuck at the airport",
         body="My flight just got cancelled and I don't know what to do, can you help me figure this out right now?",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="high", expected_sentiment="negative",
         note="in-the-moment travel crisis"),
    dict(id="F3", subject="we need to talk right now",
         body="We need to talk right now, please call me as soon as you can.",
         to="partner@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="high", expected_sentiment="negative",
         note="minimal text but clearly urgent, no keywords like urgent/asap"),
    dict(id="F4", subject="apartment is flooding",
         body="Water is coming in fast, my apartment is flooding, I need help immediately.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="high", expected_sentiment="negative",
         note="physical emergency"),
    dict(id="F5", subject="someone broke into the house",
         body="I think someone broke into the house, everything's a mess, call me back right now.",
         to="partner@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="high", expected_sentiment="negative",
         note="safety emergency"),
    dict(id="F6", subject="car broke down on the highway",
         body="The car just died on the highway shoulder, I need you to come get me right now, it's not safe here.",
         to="partner@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="high", expected_sentiment="negative",
         note="safety + logistics emergency"),
    dict(id="F7", subject="not okay",
         body="I'm not okay right now, please call me when you see this.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="high", expected_sentiment="negative",
         note="minimal text, emotional crisis, no urgency keywords at all"),
    dict(id="F8", subject="lost my passport, flight leaves in an hour",
         body="I lost my passport somewhere in the airport and my flight leaves in an hour, please call me immediately.",
         to="partner@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="high", expected_sentiment="negative",
         note="hard time pressure"),

    # ── Block G: Other - low (newsletters, marketing, receipts) ─────────────
    dict(id="G1", subject="Your weekly digest from TechNews",
         body="Here's this week's top stories in tech. Unsubscribe anytime.",
         to="subscriber@gmail.com", from_addr="digest@technews.com",
         expected_category="Other", expected_priority="low", expected_sentiment="neutral",
         note="newsletter"),
    dict(id="G2", subject="20% off this weekend only!",
         body="Don't miss our biggest sale of the season, 20% off everything this weekend. Shop now!",
         to="customer@gmail.com", from_addr="deals@retailstore.com",
         expected_category="Other", expected_priority="low", expected_sentiment="positive",
         note="marketing hype but genuinely low priority to the reader"),
    dict(id="G3", subject="Your subscription receipt",
         body="This confirms your monthly subscription payment was processed successfully. No action needed.",
         to="customer@gmail.com", from_addr="billing@streamingservice.com",
         expected_category="Other", expected_priority="low", expected_sentiment="neutral",
         note="automated receipt"),
    dict(id="G4", subject="New blog post: 10 tips for productivity",
         body="Check out our latest post on productivity tips, published this morning.",
         to="subscriber@gmail.com", from_addr="blog@productivityco.com",
         expected_category="Other", expected_priority="low", expected_sentiment="positive",
         note="content notification"),
    dict(id="G5", subject="Unsubscribe confirmed",
         body="You've been successfully unsubscribed from this mailing list. Sorry to see you go.",
         to="customer@gmail.com", from_addr="noreply@mailinglist.com",
         expected_category="Other", expected_priority="low", expected_sentiment="neutral",
         note="automated confirmation"),
    dict(id="G6", subject="Your monthly bank statement is ready",
         body="Your statement for last month is now available to view online.",
         to="customer@gmail.com", from_addr="statements@bank.com",
         expected_category="Other", expected_priority="low", expected_sentiment="neutral",
         note="routine financial notification"),
    dict(id="G7", subject="Community newsletter - local events this month",
         body="Check out what's happening in your neighborhood this month, from farmers markets to concerts.",
         to="resident@gmail.com", from_addr="community@localnews.org",
         expected_category="Other", expected_priority="low", expected_sentiment="positive",
         note="community newsletter"),
    dict(id="G8", subject="Podcast recommendations for you",
         body="Based on what you've been listening to, here are some new episodes you might like.",
         to="listener@gmail.com", from_addr="recommendations@podcastapp.com",
         expected_category="Other", expected_priority="low", expected_sentiment="neutral",
         note="automated recommendation"),
    dict(id="G9", subject="Your order has shipped",
         body="Good news, your order is on its way. Tracking info is attached.",
         to="customer@gmail.com", from_addr="orders@onlinestore.com",
         expected_category="Other", expected_priority="low", expected_sentiment="positive",
         note="shipping notification"),
    dict(id="G10", subject="Gym membership renews automatically next month",
         body="Just a heads up that your membership will renew automatically next month, no action needed if you're staying.",
         to="member@gmail.com", from_addr="billing@gymco.com",
         expected_category="Other", expected_priority="low", expected_sentiment="neutral",
         note="future auto-renewal FYI"),
    dict(id="G11", subject="New features added to your app",
         body="We've rolled out some new features you might enjoy, check them out whenever you open the app next.",
         to="user@gmail.com", from_addr="product@appco.com",
         expected_category="Other", expected_priority="low", expected_sentiment="positive",
         note="product update notice"),
    dict(id="G12", subject="Quick survey about your recent experience",
         body="We'd love your feedback, the survey takes about 2 minutes and is completely optional.",
         to="customer@gmail.com", from_addr="feedback@retailstore.com",
         expected_category="Other", expected_priority="low", expected_sentiment="neutral",
         note="optional survey"),

    # ── Block H: Other - medium ───────────────────────────────────────────
    dict(id="H1", subject="Delivery attempt failed - please reschedule",
         body="We tried to deliver your package today but no one was home. Please reschedule delivery within the next few days.",
         to="customer@gmail.com", from_addr="delivery@shippingco.com",
         expected_category="Other", expected_priority="medium", expected_sentiment="neutral",
         note="needs action, mild time window"),
    dict(id="H2", subject="Please verify your email address",
         body="To keep using our service without interruption, please verify your email address within the next few days.",
         to="user@gmail.com", from_addr="noreply@appco.com",
         expected_category="Other", expected_priority="medium", expected_sentiment="neutral",
         note="account action needed, soft deadline"),
    dict(id="H3", subject="Please confirm your upcoming appointment",
         body="Your appointment is coming up next week, please confirm you'll be attending.",
         to="patient@gmail.com", from_addr="clinic@healthcareco.com",
         expected_category="Other", expected_priority="medium", expected_sentiment="neutral",
         note="confirmation needed"),
    dict(id="H4", subject="Your password will expire in 7 days",
         body="For security, please update your password within the next 7 days to avoid being locked out.",
         to="user@gmail.com", from_addr="security@companyportal.com",
         expected_category="Other", expected_priority="medium", expected_sentiment="neutral",
         note="soft security deadline"),
    dict(id="H5", subject="Flight check-in is now open",
         body="Check-in for your upcoming flight is now open. Complete it before departure to save time at the airport.",
         to="traveler@gmail.com", from_addr="checkin@airline.com",
         expected_category="Other", expected_priority="medium", expected_sentiment="neutral",
         note="time-relevant but not urgent yet"),
    dict(id="H6", subject="Update your payment method",
         body="Your payment method on file is about to expire. Please update it before your next billing date to avoid interruption.",
         to="customer@gmail.com", from_addr="billing@streamingservice.com",
         expected_category="Other", expected_priority="medium", expected_sentiment="neutral",
         note="upcoming billing issue"),

    # ── Block I: Other - high (legit non-spam alerts) ────────────────────
    dict(id="I1", subject="Unusual sign-in attempt detected",
         body="We detected a sign-in attempt from a new device. If this wasn't you, please secure your account immediately.",
         to="user@gmail.com", from_addr="security@bigtechco.com",
         expected_category="Other", expected_priority="high", expected_sentiment="negative",
         note="legit security alert, time-sensitive"),
    dict(id="I2", subject="Account will be suspended in 24 hours",
         body="Your recent payment failed and your account will be suspended in 24 hours unless you update your billing information.",
         to="customer@gmail.com", from_addr="billing@saascompany.com",
         expected_category="Other", expected_priority="high", expected_sentiment="negative",
         note="real consequence, hard deadline — also resembles a phishing pattern, tests spam/priority interaction"),
    dict(id="I3", subject="Severe weather warning for your area",
         body="A severe storm warning has been issued for your area. Take shelter immediately and avoid travel.",
         to="resident@gmail.com", from_addr="alerts@weatherservice.gov",
         expected_category="Other", expected_priority="high", expected_sentiment="negative",
         note="safety alert"),
    dict(id="I4", subject="Final boarding call",
         body="This is the final boarding call for your flight. Please proceed to the gate immediately, doors close in 10 minutes.",
         to="traveler@gmail.com", from_addr="alerts@airline.com",
         expected_category="Other", expected_priority="high", expected_sentiment="neutral",
         note="hard real-time deadline"),

    # ── Block J: adversarial / mixed-signal cases ─────────────────────────
    dict(id="J1", subject="You got the promotion!",
         body="Congratulations, you got the promotion! Please confirm by tomorrow morning so we can announce it at the all-hands.",
         to="employee@company.com", from_addr="manager@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="positive",
         note="positive sentiment + high priority — probes the rejected 'positive suppresses priority' hypothesis"),
    dict(id="J2", subject="ok this actually can't wait",
         body="lol ok this actually can't wait, call me the second you see this, it's about the wedding venue, they need an answer today",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="high", expected_sentiment="neutral",
         note="casual/sarcastic opener masking a real same-day deadline"),
    dict(id="J3", subject="bad day",
         body="Ugh today was such a bad day, everything went wrong, just needed to vent, don't worry about replying to this.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="low", expected_sentiment="negative",
         note="negative sentiment but explicitly no action needed — tests whether negative wrongly inflates priority"),
    dict(id="J4", subject="URGENT!!! FINAL HOURS!!! Everything must go!",
         body="URGENT!!! Final hours of our biggest sale ever, everything must go, shop now before it's too late!!!",
         to="customer@gmail.com", from_addr="deals@retailstore.com",
         expected_category="Other", expected_priority="low", expected_sentiment="positive",
         note="urgency keywords used purely as marketing hype — should NOT read as genuinely high priority"),
    dict(id="J5", subject="Server issue from last week - resolved",
         body="FYI, the urgent server issue from last week has been fully resolved. No action needed on your end.",
         to="eng@company.com", from_addr="it@company.com",
         expected_category="Work", expected_priority="low", expected_sentiment="neutral",
         note="contains the word 'urgent' but describing a past, resolved issue — pure keyword-matching trap"),
    dict(id="J6", subject="call me now",
         body="Call me now.",
         to="employee@company.com", from_addr="boss@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="neutral",
         note="extremely short, no urgency keywords, from a boss"),
    dict(id="J7", subject="hey",
         body="hey",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="low", expected_sentiment="neutral",
         note="minimal text, near-empty body"),
    dict(id="J8", subject="catching up",
         body="Hey! It's been a while, hope everything's going well on your end. Things have been pretty busy here lately but nothing too crazy, mostly just work and trying to get outside more on weekends. We should catch up sometime soon, no particular reason, just been thinking about you. Let me know whenever works, genuinely no rush at all.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="low", expected_sentiment="positive",
         note="long rambling text but ultimately low priority — tests whether length alone inflates score"),
    dict(id="J9", subject="Appointment reminder - Dr. Smith's office",
         body="This is a reminder of your upcoming appointment with Dr. Smith next Tuesday at 10am. Please arrive 15 minutes early.",
         to="patient@gmail.com", from_addr="scheduling@clinic.com",
         expected_category="Other", expected_priority="medium", expected_sentiment="neutral",
         note="institutional sender about a personal matter — ambiguous category, expect Other not Personal"),
    dict(id="J10", subject="Third time this issue has happened",
         body="This is the third time I've had this issue, I am extremely frustrated and need this resolved today or I'm canceling my contract.",
         to="support@company.com", from_addr="client@othercompany.com",
         expected_category="Work", expected_priority="high", expected_sentiment="negative",
         note="angry customer escalation, real business consequence"),
    dict(id="J11", subject="sorry I missed your call",
         body="Sorry I missed your call yesterday, was swamped. No big deal though, we can catch up whenever works for you.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="low", expected_sentiment="neutral",
         note="apologetic tone but explicitly low-stakes"),
    dict(id="J12", subject="Password reset link (expires in 15 minutes)",
         body="Here is the password reset link you requested. It expires in 15 minutes, so please use it soon.",
         to="user@gmail.com", from_addr="noreply@webapp.com",
         expected_category="Other", expected_priority="medium", expected_sentiment="neutral",
         note="hard countdown but self-initiated, low real stakes if ignored — phishing-shaped but legitimate"),
    dict(id="J13", subject="REMINDER: OFFICE CLOSED FOR HOLIDAY MONDAY",
         body="JUST A REMINDER THAT THE OFFICE WILL BE CLOSED THIS COMING MONDAY FOR THE HOLIDAY. ENJOY THE LONG WEEKEND.",
         to="staff@company.com", from_addr="admin@company.com",
         expected_category="Work", expected_priority="low", expected_sentiment="positive",
         note="all-caps formatting (spam-like surface features) but genuinely low-priority content"),
    dict(id="J14", subject="911",
         body="911. My office. Now.",
         to="employee@company.com", from_addr="boss@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="negative",
         note="extremely terse, no standard urgency vocabulary at all"),
    dict(id="J15", subject="please send report today",
         body="please you must send report today is very important the boss is asking many times",
         to="colleague@company.com", from_addr="teammate@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="neutral",
         note="non-native/broken English phrasing of a genuine same-day escalation"),
    dict(id="J16", subject="Great job on the presentation!",
         body="Great job on the presentation today! Whenever you get a chance this week, could you send me the slides so I can share with the wider team?",
         to="colleague@company.com", from_addr="manager@company.com",
         expected_category="Work", expected_priority="medium", expected_sentiment="positive",
         note="positive tone with a real but soft ask"),
    dict(id="J17", subject="kind of an emergency",
         body="hey no worries if you're busy but honestly this is kind of an emergency, my landlord is evicting me tomorrow, can we talk tonight?",
         to="friend@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="high", expected_sentiment="negative",
         note="soft/apologetic opening tone masking a real same-day crisis"),
    dict(id="J18", subject="move today's 3pm meeting?",
         body="Can we move today's 3pm meeting to 4pm instead? Let me know if that doesn't work for you.",
         to="colleague@company.com", from_addr="colleague2@company.com",
         expected_category="Work", expected_priority="medium", expected_sentiment="neutral",
         note="same-day but low-stakes reschedule"),
    dict(id="J19", subject="Industry trends worth noting",
         body="Wanted to share a few industry trends I've been reading about lately - nothing actionable, just thought it was interesting context for the team. First, there's been a broader shift toward remote-first tooling across the sector. Second, several competitors have started publishing more transparent pricing. No follow-up needed, just sharing for awareness.",
         to="team@company.com", from_addr="colleague@company.com",
         expected_category="Work", expected_priority="low", expected_sentiment="neutral",
         note="long professional email but explicitly no action needed"),
    dict(id="J20", subject="scared",
         body="im scared someone is following me call the police or call me now",
         to="partner@gmail.com", from_addr="me@gmail.com",
         expected_category="Personal", expected_priority="high", expected_sentiment="negative",
         note="lowercase, no punctuation, texting-style safety emergency"),
    dict(id="J21", subject="quick feedback form",
         body="Whenever you have a moment over the next month or so, could you fill out this short feedback form? Thanks in advance, no rush at all.",
         to="participant@gmail.com", from_addr="research@company.com",
         expected_category="Other", expected_priority="low", expected_sentiment="positive",
         note="deadline is a month out despite being phrased as a request — should not read as medium"),
    dict(id="J22", subject="car accident, might be late",
         body="Car accident on the way to the client site, everyone's fine but I might be late. Someone needs to cover the 2pm meeting ASAP.",
         to="team@company.com", from_addr="colleague@company.com",
         expected_category="Work", expected_priority="high", expected_sentiment="negative",
         note="real emergency reported casually, has 'ASAP' but the real signal is the accident context"),
]

assert len(TEST_EMAILS) == 100, f"expected 100 emails, got {len(TEST_EMAILS)}"
assert len(set(e['id'] for e in TEST_EMAILS)) == 100, "duplicate ids"
