"""
synthetic_priority_train_batch5.py — batch 5/5 (final). See batch1 docstring.
"""

ROWS = [
    # ── Work - low (11) ──────────────────────────────────────────────────
    dict(id="T5-W-L1", subject="Anchor Point Marina - dock boards replaced",
         body="Replaced a few worn boards on dock C this week, all set. Nothing needed from anyone.",
         to="staff@anchorpointmarina.com", from_addr="dockmaster@anchorpointmarina.com",
         true_category="Work", true_priority=0.14, true_bucket="low"),
    dict(id="T5-W-L2", subject="Chapter House Books - staff picks shelf refreshed",
         body="Updated the staff picks shelf with some new titles, looks good. Just wanted to mention it.",
         to="staff@chapterhousebooks.com", from_addr="manager@chapterhousebooks.com",
         true_category="Work", true_priority=0.13, true_bucket="low"),
    dict(id="T5-W-L3", subject="Rising Stars Afterschool - craft supplies restocked",
         body="Restocked the craft supply bins for next week's projects, all set for the group.",
         to="staff@risingstarsafterschool.com", from_addr="director@risingstarsafterschool.com",
         true_category="Work", true_priority=0.15, true_bucket="low"),
    dict(id="T5-W-L4", subject="Coastal HVAC - new van wrap looks great",
         body="The new van wrap design got installed today, looks sharp. No action needed, just sharing.",
         to="techs@coastalhvac.com", from_addr="owner@coastalhvac.com",
         true_category="Work", true_priority=0.12, true_bucket="low"),
    dict(id="T5-W-L5", subject="Cellar Door - new glassware arrived",
         body="New wine glasses arrived and are already washed and stocked behind the bar. Nothing further needed.",
         to="staff@cellardoorwinebar.com", from_addr="manager@cellardoorwinebar.com",
         true_category="Work", true_priority=0.14, true_bucket="low"),
    dict(id="T5-W-L6", subject="Pinnacle Tutoring - new whiteboard installed",
         body="Installed the new whiteboard in room 2, tutors can use it starting this week. FYI only.",
         to="tutors@pinnacletutoring.com", from_addr="director@pinnacletutoring.com",
         true_category="Work", true_priority=0.13, true_bucket="low"),
    dict(id="T5-W-L7", subject="Presswork Printing - new paper stock sample",
         body="Got a sample of the new recycled paper stock, feels nice, sitting on the counter if you want to check it out.",
         to="staff@presswork printing.com".replace(" ", ""), from_addr="manager@presswork printing.com".replace(" ", ""),
         true_category="Work", true_priority=0.15, true_bucket="low"),
    dict(id="T5-W-L8", subject="Fluff & Fold Grooming - new dryer installed",
         body="New high-velocity dryer got installed today, cuts drying time nicely. Nothing needed from anyone.",
         to="groomers@fluffandfold.com", from_addr="owner@fluffandfold.com",
         true_category="Work", true_priority=0.14, true_bucket="low"),
    dict(id="T5-W-L9", subject="Sunbeam Solar - training video uploaded",
         body="Uploaded the new install training video to the shared drive, watch whenever convenient, no deadline.",
         to="installers@sunbeamsolar.com", from_addr="training@sunbeamsolar.com",
         true_category="Work", true_priority=0.16, true_bucket="low"),
    dict(id="T5-W-L10", subject="Rapid Courier - new bike racks installed",
         body="New bike racks are up outside the depot, should make mornings a bit easier. Just an FYI.",
         to="couriers@rapidcourier.com", from_addr="dispatch@rapidcourier.com",
         true_category="Work", true_priority=0.13, true_bucket="low"),
    dict(id="T5-W-L11", subject="nice work this week",
         body="just wanted to say the team handled a busy week really well, appreciate everyone, no reply needed",
         to="techs@coastalhvac.com", from_addr="owner@coastalhvac.com",
         true_category="Work", true_priority=0.15, true_bucket="low"),

    # ── Work - medium (11) ───────────────────────────────────────────────
    dict(id="T5-W-M1", subject="Need the slip renewal list reviewed",
         body="Could you review the slip renewal list sometime this week? A few need follow-up before the season starts.",
         to="dockmaster@anchorpointmarina.com", from_addr="office@anchorpointmarina.com",
         true_category="Work", true_priority=0.38, true_bucket="medium"),
    dict(id="T5-W-M2", subject="Need the event schedule finalized",
         body="Could you finalize the author event schedule sometime this week? Want to start promoting soon.",
         to="manager@chapterhousebooks.com", from_addr="events@chapterhousebooks.com",
         true_category="Work", true_priority=0.36, true_bucket="medium"),
    dict(id="T5-W-M3", subject="Need the field trip permission slips collected",
         body="Could you follow up on the missing permission slips sometime this week? Trip's coming up soon.",
         to="staff@risingstarsafterschool.com", from_addr="director@risingstarsafterschool.com",
         true_category="Work", true_priority=0.41, true_bucket="medium"),
    dict(id="T5-W-M4", subject="Need the parts order confirmed",
         body="Could you confirm this week's parts order sometime today or tomorrow? Need it in before next week's jobs.",
         to="techs@coastalhvac.com", from_addr="office@coastalhvac.com",
         true_category="Work", true_priority=0.42, true_bucket="medium"),
    dict(id="T5-W-M5", subject="Need the wine list update approved",
         body="Could you approve the updated wine list sometime this week? Want to have it printed before the weekend.",
         to="manager@cellardoorwinebar.com", from_addr="sommelier@cellardoorwinebar.com",
         true_category="Work", true_priority=0.37, true_bucket="medium"),
    dict(id="T5-W-M6", subject="Need the student progress reports done",
         body="Could you finish the quarterly progress reports sometime this week? Parents are expecting them soon.",
         to="tutors@pinnacletutoring.com", from_addr="director@pinnacletutoring.com",
         true_category="Work", true_priority=0.40, true_bucket="medium"),
    dict(id="T5-W-M7", subject="Need the proof approved before we print",
         body="Could you approve the final proof sometime today or tomorrow? Press run is scheduled for later this week.",
         to="staff@presswork printing.com".replace(" ", ""), from_addr="manager@presswork printing.com".replace(" ", ""),
         true_category="Work", true_priority=0.43, true_bucket="medium"),
    dict(id="T5-W-M8", subject="Need the appointment book reviewed",
         body="Could you look over next week's appointment book sometime this week? A couple slots need double-checking.",
         to="groomers@fluffandfold.com", from_addr="owner@fluffandfold.com",
         true_category="Work", true_priority=0.34, true_bucket="medium"),
    dict(id="T5-W-M9", subject="Need the site survey scheduled",
         body="Could you schedule the site survey for the Hendricks install sometime this week? Customer's waiting to move forward.",
         to="installers@sunbeamsolar.com", from_addr="sales@sunbeamsolar.com",
         true_category="Work", true_priority=0.39, true_bucket="medium"),
    dict(id="T5-W-M10", subject="Need the route assignments confirmed",
         body="Could you confirm tomorrow's route assignments sometime today? Want to make sure everyone's covered.",
         to="couriers@rapidcourier.com", from_addr="dispatch@rapidcourier.com",
         true_category="Work", true_priority=0.38, true_bucket="medium"),
    dict(id="T5-W-M11", subject="need feedback on the new booking system",
         body="could you try out the new booking system sometime this week and let me know what you think before we switch over fully",
         to="manager@cellardoorwinebar.com", from_addr="sommelier@cellardoorwinebar.com",
         true_category="Work", true_priority=0.35, true_bucket="medium"),

    # ── Work - high (12) ─────────────────────────────────────────────────
    dict(id="T5-W-H1", subject="Boat is taking on water at the dock",
         body="One of the boats at dock C is taking on water fast, need everyone available down there right now.",
         to="staff@anchorpointmarina.com", from_addr="dockmaster@anchorpointmarina.com",
         true_category="Work", true_priority=0.94, true_bucket="high"),
    dict(id="T5-W-H2", subject="Water pipe burst above the rare book section",
         body="A pipe just burst above the rare books, water's coming down fast, need everyone helping move stock right now.",
         to="staff@chapterhousebooks.com", from_addr="manager@chapterhousebooks.com",
         true_category="Work", true_priority=0.92, true_bucket="high"),
    dict(id="T5-W-H3", subject="Kid is missing from the afterschool group",
         body="We can't find one of the kids from the group, need everyone searching right now and parents called immediately.",
         to="staff@risingstarsafterschool.com", from_addr="director@risingstarsafterschool.com",
         true_category="Work", true_priority=0.99, true_bucket="high"),
    dict(id="T5-W-H4", subject="Customer has no heat and it's freezing tonight",
         body="A customer's furnace died completely and it's below freezing tonight with young kids in the house, need someone out there immediately.",
         to="techs@coastalhvac.com", from_addr="dispatch@coastalhvac.com",
         true_category="Work", true_priority=0.90, true_bucket="high"),
    dict(id="T5-W-H5", subject="Guest is choking, need help now",
         body="A guest is choking at table 4 right now, need everyone trained in first aid over here immediately.",
         to="manager@cellardoorwinebar.com", from_addr="staff@cellardoorwinebar.com",
         true_category="Work", true_priority=0.99, true_bucket="high"),
    dict(id="T5-W-H6", subject="Student having a panic attack, need help now",
         body="One of the students is having a severe panic attack right now, need you back here immediately.",
         to="director@pinnacletutoring.com", from_addr="tutors@pinnacletutoring.com",
         true_category="Work", true_priority=0.87, true_bucket="high"),
    dict(id="T5-W-H7", subject="Press jammed and is smoking",
         body="The big press just jammed and is smoking badly, need it shut down and someone here right now.",
         to="staff@presswork printing.com".replace(" ", ""), from_addr="manager@presswork printing.com".replace(" ", ""),
         true_category="Work", true_priority=0.93, true_bucket="high"),
    dict(id="T5-W-H8", subject="Dog bit a groomer, need help now",
         body="A dog just bit one of the groomers pretty badly, need first aid and possibly 911 right now.",
         to="owner@fluffandfold.com", from_addr="groomers@fluffandfold.com",
         true_category="Work", true_priority=0.96, true_bucket="high"),
    dict(id="T5-W-H9", subject="Installer fell off the roof",
         body="An installer just fell off the roof on site, we've called 911, need you here right now.",
         to="installers@sunbeamsolar.com", from_addr="crew@sunbeamsolar.com",
         true_category="Work", true_priority=0.99, true_bucket="high"),
    dict(id="T5-W-H10", subject="Courier was in an accident on route",
         body="One of our couriers was just in an accident on their route, need dispatch coordinating with EMS immediately.",
         to="dispatch@rapidcourier.com", from_addr="courier@rapidcourier.com",
         true_category="Work", true_priority=0.97, true_bucket="high"),
    dict(id="T5-W-H11", subject="get here now",
         body="get down to the dock right now, the boat is sinking fast",
         to="staff@anchorpointmarina.com", from_addr="dockmaster@anchorpointmarina.com",
         true_category="Work", true_priority=0.95, true_bucket="high"),
    dict(id="T5-W-H12", subject="call now",
         body="call me right now, we have no heat for a family with a newborn, need a tech out there tonight",
         to="techs@coastalhvac.com", from_addr="dispatch@coastalhvac.com",
         true_category="Work", true_priority=0.91, true_bucket="high"),

    # ── Personal - low (11) ──────────────────────────────────────────────
    dict(id="T5-P-L1", subject="second mom update",
         body="Hope you're doing well, nothing new here really, just wanted to check in since it's been a while.",
         to="roommateparent@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.15, true_bucket="low"),
    dict(id="T5-P-L2", subject="date night went great",
         body="Just wanted you to know date night went really well last week, thanks for the recommendation on the restaurant.",
         to="daughterspartner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.14, true_bucket="low"),
    dict(id="T5-P-L3", subject="your kid helped me carry groceries",
         body="Your teenager helped me carry groceries in today without even being asked, made my whole day, wanted you to know.",
         to="neighborparent@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.13, true_bucket="low"),
    dict(id="T5-P-L4", subject="choir sounded amazing this week",
         body="The choir sounded incredible this week, you really outdid yourself with the arrangement, just wanted to say so.",
         to="choirdirector@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.15, true_bucket="low"),
    dict(id="T5-P-L5", subject="good run this morning",
         body="Had a really good run with the club this morning, weather was perfect, wish you'd been there.",
         to="runningclubfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.16, true_bucket="low"),
    dict(id="T5-P-L6", subject="in-law's mom sent the sweetest card",
         body="Your mom sent us the sweetest card in the mail today, made me tear up a little, thank her for us.",
         to="inlawparent@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.14, true_bucket="low"),
    dict(id="T5-P-L7", subject="foster kiddo had a great day",
         body="The kiddo had a really good day today, first time smiling that much since placement, wanted to share the good news.",
         to="fosterparentfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.17, true_bucket="low"),
    dict(id="T5-P-L8", subject="brother's wife found the funniest meme",
         body="Found this meme and immediately thought you'd get it, sending it your way, no context needed.",
         to="brotherswife@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.12, true_bucket="low"),
    dict(id="T5-P-L9", subject="thank you for the letter",
         body="Got your letter today, made my whole week, will write back properly soon, just wanted to say thank you.",
         to="penpal@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.16, true_bucket="low"),
    dict(id="T5-P-L10", subject="group was really supportive today",
         body="Today's meeting was really good, felt supported by everyone, just wanted to say thanks for always showing up.",
         to="supportgroupfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.15, true_bucket="low"),
    dict(id="T5-P-L11", subject="lol the dog and the mail carrier",
         body="lol the dog made friends with the mail carrier today, sending you the picture, it's too cute",
         to="runningclubfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.12, true_bucket="low"),

    # ── Personal - medium (11) ───────────────────────────────────────────
    dict(id="T5-P-M1", subject="need to plan the visit with the kids",
         body="Trying to plan a visit with the grandkids soon, are you free a weekend next month? Let me know so I can plan around it.",
         to="roommateparent@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.38, true_bucket="medium"),
    dict(id="T5-P-M2", subject="need to confirm dinner with you two",
         body="Trying to lock in a dinner date with you both soon, does next weekend work? Let me know so I can book somewhere.",
         to="daughterspartner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.34, true_bucket="medium"),
    dict(id="T5-P-M3", subject="need to borrow the ladder again",
         body="Could I borrow your ladder again sometime this week? Trying to get the gutters done before it rains.",
         to="neighborparent@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.30, true_bucket="medium"),
    dict(id="T5-P-M4", subject="need the solo confirmed for sunday",
         body="Could you confirm who's singing the solo this Sunday sometime this week? Need to finalize the program.",
         to="choirdirector@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.36, true_bucket="medium"),
    dict(id="T5-P-M5", subject="need a running partner for the race",
         body="Signing up for the half marathon soon, are you in? Need to know this week before registration closes.",
         to="runningclubfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.35, true_bucket="medium"),
    dict(id="T5-P-M6", subject="need to plan the anniversary trip together",
         body="Want to plan something for their anniversary, are you free to talk logistics sometime this week?",
         to="inlawparent@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.37, true_bucket="medium"),
    dict(id="T5-P-M7", subject="need the school supply list handled",
         body="School supply list came in for the foster kiddo, could you help me get it sorted sometime this week?",
         to="fosterparentfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.39, true_bucket="medium"),
    dict(id="T5-P-M8", subject="need to sort out the shared gift",
         body="Trying to figure out the group gift for the in-laws, can you send your thoughts sometime this week?",
         to="brotherswife@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.32, true_bucket="medium"),
    dict(id="T5-P-M9", subject="need your new address soon",
         body="Want to send a package your way, can you send your current address sometime this week?",
         to="penpal@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.28, true_bucket="medium"),
    dict(id="T5-P-M10", subject="need to know if you're coming to group",
         body="Wondering if you'll be at group this week, could use your support on something, let me know when you can.",
         to="supportgroupfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.40, true_bucket="medium"),
    dict(id="T5-P-M11", subject="need an answer on the trip soon",
         body="hey, need to know by this weekend if you're still coming on the trip so I can finalize the booking",
         to="daughterspartner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.41, true_bucket="medium"),

    # ── Personal - high (12) ─────────────────────────────────────────────
    dict(id="T5-P-H1", subject="second mom, need you right now",
         body="Something happened and I really need you right now, can you call me the second you see this.",
         to="roommateparent@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.85, true_bucket="high"),
    dict(id="T5-P-H2", subject="need you both to call, urgent",
         body="Something serious happened and I need to talk to you both right away, please call as soon as you can.",
         to="daughterspartner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.83, true_bucket="high"),
    dict(id="T5-P-H3", subject="your kid is hurt next door",
         body="Your teenager just got hurt playing out front, nothing life-threatening but you should come now.",
         to="neighborparent@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.88, true_bucket="high"),
    dict(id="T5-P-H4", subject="choir director, need you now",
         body="Something happened right before the service and I need you here immediately, please come now.",
         to="choirdirector@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.80, true_bucket="high"),
    dict(id="T5-P-H5", subject="collapsed during the run, need help",
         body="Someone from the running group just collapsed on the trail, we've called 911, come to the trailhead now if you can.",
         to="runningclubfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.96, true_bucket="high"),
    dict(id="T5-P-H6", subject="in-law's mom fell, at the hospital",
         body="Your mom just fell and we're at the hospital now, please call me the second you see this.",
         to="inlawparent@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.97, true_bucket="high"),
    dict(id="T5-P-H7", subject="foster kiddo had a bad reaction",
         body="The kiddo is having a bad reaction to something, heading to urgent care now, please call me right away.",
         to="fosterparentfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.95, true_bucket="high"),
    dict(id="T5-P-H8", subject="brother's wife, call me now",
         body="Something happened with your husband, my brother, please call me the second you see this.",
         to="brotherswife@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.93, true_bucket="high"),
    dict(id="T5-P-H9", subject="need you, can't do this alone right now",
         body="Having a really hard moment and don't want to be alone, can you call or come by as soon as you can?",
         to="supportgroupfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.82, true_bucket="high"),
    dict(id="T5-P-H10", subject="call me now",
         body="please call me right now, it's urgent, i'll explain when you call",
         to="roommateparent@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.84, true_bucket="high"),
    dict(id="T5-P-H11", subject="911 need you",
         body="calling 911 now, please come to the house right away",
         to="inlawparent@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.98, true_bucket="high"),
    dict(id="T5-P-H12", subject="help",
         body="need help right now, please call, can't talk long",
         to="fosterparentfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.90, true_bucket="high"),

    # ── Other - low (12) ─────────────────────────────────────────────────
    dict(id="T5-O-L1", subject="Your marina slip renewal receipt",
         body="Here's your receipt for the slip renewal, thanks. No action needed.",
         to="boatowner@gmail.com", from_addr="billing@anchorpointmarina.com",
         true_category="Other", true_priority=0.11, true_bucket="low"),
    dict(id="T5-O-L2", subject="Your bookstore loyalty points update",
         body="You've earned enough points for a free coffee at the cafe counter, redeem whenever you're in next.",
         to="customer@gmail.com", from_addr="rewards@chapterhousebooks.com",
         true_category="Other", true_priority=0.12, true_bucket="low"),
    dict(id="T5-O-L3", subject="Afterschool program - photo day reminder for next month",
         body="Photo day is next month, no need to do anything yet, just a heads up for planning ahead.",
         to="parent@gmail.com", from_addr="office@risingstarsafterschool.com",
         true_category="Other", true_priority=0.14, true_bucket="low"),
    dict(id="T5-O-L4", subject="Your HVAC maintenance visit summary",
         body="Here's a summary of today's routine maintenance visit, everything checked out fine.",
         to="customer@gmail.com", from_addr="service@coastalhvac.com",
         true_category="Other", true_priority=0.13, true_bucket="low"),
    dict(id="T5-O-L5", subject="Your wine club shipment is on the way",
         body="This month's wine club selection shipped today, enjoy. No action needed.",
         to="member@gmail.com", from_addr="club@cellardoorwinebar.com",
         true_category="Other", true_priority=0.11, true_bucket="low"),
    dict(id="T5-O-L6", subject="Tutoring session recap for this week",
         body="Here's a quick recap of this week's session, went well, nothing to flag. See you next week.",
         to="parent@gmail.com", from_addr="tutors@pinnacletutoring.com",
         true_category="Other", true_priority=0.15, true_bucket="low"),
    dict(id="T5-O-L7", subject="Your print order is ready for pickup",
         body="Your order is ready whenever you'd like to swing by, no rush, we're open till 6.",
         to="customer@gmail.com", from_addr="orders@presswork printing.com".replace(" ", ""),
         true_category="Other", true_priority=0.13, true_bucket="low"),
    dict(id="T5-O-L8", subject="Grooming appointment reminder for next week",
         body="Just a friendly reminder your pup has a grooming appointment next week, nothing to do until then.",
         to="petowner@gmail.com", from_addr="scheduling@fluffandfold.com",
         true_category="Other", true_priority=0.14, true_bucket="low"),
    dict(id="T5-O-L9", subject="Your solar panels produced well this month",
         body="Your system had a great production month, check the app whenever you're curious about the numbers.",
         to="homeowner@gmail.com", from_addr="monitoring@sunbeamsolar.com",
         true_category="Other", true_priority=0.12, true_bucket="low"),
    dict(id="T5-O-L10", subject="Your package was delivered",
         body="Your package was delivered to the front desk, pick up whenever convenient.",
         to="customer@gmail.com", from_addr="notify@rapidcourier.com",
         true_category="Other", true_priority=0.11, true_bucket="low"),
    dict(id="T5-O-L11", subject="Unemployment office - your claim status is unchanged",
         body="Just confirming your claim status hasn't changed since last update, no action needed at this time.",
         to="claimant@gmail.com", from_addr="notices@stateunemployment.gov",
         true_category="Other", true_priority=0.16, true_bucket="low"),
    dict(id="T5-O-L12", subject="your subscription box shipped",
         body="this month's box shipped out today, tracking is attached, enjoy whenever it arrives",
         to="subscriber@gmail.com", from_addr="orders@monthlycratebox.com",
         true_category="Other", true_priority=0.12, true_bucket="low"),

    # ── Other - medium (11) ──────────────────────────────────────────────
    dict(id="T5-O-M1", subject="Please renew your slip contract soon",
         body="Your slip contract is up for renewal, please respond within the next two weeks to keep your spot.",
         to="boatowner@gmail.com", from_addr="office@anchorpointmarina.com",
         true_category="Other", true_priority=0.37, true_bucket="medium"),
    dict(id="T5-O-M2", subject="Please pick up your holds soon",
         body="A couple books you placed on hold are ready, please pick them up within the next week or they'll be released.",
         to="patron@gmail.com", from_addr="holds@chapterhousebooks.com",
         true_category="Other", true_priority=0.32, true_bucket="medium"),
    dict(id="T5-O-M3", subject="Please complete enrollment for next semester",
         body="Please complete the re-enrollment form within the next two weeks to keep your child's spot in the program.",
         to="parent@gmail.com", from_addr="office@risingstarsafterschool.com",
         true_category="Other", true_priority=0.42, true_bucket="medium"),
    dict(id="T5-O-M4", subject="Filter replacement recommended soon",
         body="Your system's filter is due for replacement, please schedule service within the next couple weeks.",
         to="customer@gmail.com", from_addr="service@coastalhvac.com",
         true_category="Other", true_priority=0.34, true_bucket="medium"),
    dict(id="T5-O-M5", subject="Please update your wine club preferences",
         body="We're finalizing next quarter's selections, please update your preferences within the next week if you'd like changes.",
         to="member@gmail.com", from_addr="club@cellardoorwinebar.com",
         true_category="Other", true_priority=0.30, true_bucket="medium"),
    dict(id="T5-O-M6", subject="Please confirm the makeup session time",
         body="We need to reschedule a missed session, please confirm a time within the next few days.",
         to="parent@gmail.com", from_addr="tutors@pinnacletutoring.com",
         true_category="Other", true_priority=0.36, true_bucket="medium"),
    dict(id="T5-O-M7", subject="Please approve the revised proof soon",
         body="We made the changes you requested, please approve the revised proof within the next couple days so we stay on schedule.",
         to="customer@gmail.com", from_addr="orders@presswork printing.com".replace(" ", ""),
         true_category="Other", true_priority=0.40, true_bucket="medium"),
    dict(id="T5-O-M8", subject="Please confirm vaccination records before your visit",
         body="We need current vaccination records before your pup's next visit, please send them within the next week.",
         to="petowner@gmail.com", from_addr="scheduling@fluffandfold.com",
         true_category="Other", true_priority=0.33, true_bucket="medium"),
    dict(id="T5-O-M9", subject="Please review a dip in your system's output",
         body="We noticed a drop in your panels' output, please let us know if you'd like a technician to check within the next couple weeks.",
         to="homeowner@gmail.com", from_addr="monitoring@sunbeamsolar.com",
         true_category="Other", true_priority=0.38, true_bucket="medium"),
    dict(id="T5-O-M10", subject="Delivery attempt failed, please reschedule soon",
         body="We couldn't deliver your package today, please reschedule within the next few days before it's returned to sender.",
         to="customer@gmail.com", from_addr="notify@rapidcourier.com",
         true_category="Other", true_priority=0.35, true_bucket="medium"),
    dict(id="T5-O-M11", subject="please submit your job search log soon",
         body="your weekly job search log is due within the next few days to keep your claim active, please submit when you can",
         to="claimant@gmail.com", from_addr="notices@stateunemployment.gov",
         true_category="Other", true_priority=0.41, true_bucket="medium"),

    # ── Other - high (9) ─────────────────────────────────────────────────
    dict(id="T5-O-H1", subject="Severe storm warning for the marina right now",
         body="A severe storm is about to hit the marina, please secure your boat or move it immediately if you're able.",
         to="boatowner@gmail.com", from_addr="alerts@anchorpointmarina.com",
         true_category="Other", true_priority=0.90, true_bucket="high"),
    dict(id="T5-O-H2", subject="Your home security alarm was triggered",
         body="Your home security system detected motion and triggered the alarm just now. Please check your camera feed or call us immediately to confirm you're safe.",
         to="homeowner@gmail.com", from_addr="monitoring@guardianhomesecurity.com",
         true_category="Other", true_priority=0.95, true_bucket="high"),
    dict(id="T5-O-H3", subject="Enrollment will be cancelled today without payment",
         body="Your child's spot will be released to the waitlist today unless payment is received, please act immediately.",
         to="parent@gmail.com", from_addr="billing@risingstarsafterschool.com",
         true_category="Other", true_priority=0.80, true_bucket="high"),
    dict(id="T5-O-H4", subject="Gas smell reported near your unit, evacuate now",
         body="A gas leak was reported near your unit, please evacuate the building immediately and do not use any switches.",
         to="customer@gmail.com", from_addr="alerts@coastalhvac.com",
         true_category="Other", true_priority=0.98, true_bucket="high"),
    dict(id="T5-O-H5", subject="Your claim is about to expire, act today",
         body="Your unemployment claim will lapse today unless you certify immediately, please log in now to avoid a gap in benefits.",
         to="claimant@gmail.com", from_addr="notices@stateunemployment.gov",
         true_category="Other", true_priority=0.83, true_bucket="high"),
    dict(id="T5-O-H6", subject="Your solar system reports a fire risk fault",
         body="Our monitoring detected a fault that can indicate a fire risk, please power down the system and call us immediately.",
         to="homeowner@gmail.com", from_addr="monitoring@sunbeamsolar.com",
         true_category="Other", true_priority=0.93, true_bucket="high"),
    dict(id="T5-O-H7", subject="Package with medication delayed, call us now",
         body="Your time-sensitive medication package was delayed in transit, please call us immediately to arrange urgent redelivery.",
         to="customer@gmail.com", from_addr="support@rapidcourier.com",
         true_category="Other", true_priority=0.87, true_bucket="high"),
    dict(id="T5-O-H8", subject="call now, break-in detected",
         body="our system detected a possible break-in at your address right now, please call us immediately or contact the police",
         to="homeowner@gmail.com", from_addr="monitoring@guardianhomesecurity.com",
         true_category="Other", true_priority=0.99, true_bucket="high"),
    dict(id="T5-O-H9", subject="urgent - your dog had a reaction during grooming",
         body="your dog had an allergic reaction during grooming today, we are taking him to the emergency vet now, please call us immediately",
         to="petowner@gmail.com", from_addr="scheduling@fluffandfold.com",
         true_category="Other", true_priority=0.96, true_bucket="high"),
]

assert len(ROWS) == 100, f"expected 100, got {len(ROWS)}"
