"""
synthetic_priority_train_batch4.py — batch 4/5. See batch1 docstring.
"""

ROWS = [
    # ── Work - low (11) ──────────────────────────────────────────────────
    dict(id="T4-W-L1", subject="Meridian Architecture - model shop reorganized",
         body="Reorganized the model shop supplies this week, everything's labeled now. Nothing needed from anyone.",
         to="staff@meridianarch.com", from_addr="office-manager@meridianarch.com",
         true_category="Work", true_priority=0.15, true_bucket="low"),
    dict(id="T4-W-L2", subject="Copperline Brewing - new tap handles arrived",
         body="New tap handles for the seasonal lineup arrived, they're in the back whenever someone wants to install them.",
         to="staff@copperlinebrewing.com", from_addr="taproom-manager@copperlinebrewing.com",
         true_category="Work", true_priority=0.14, true_bucket="low"),
    dict(id="T4-W-L3", subject="Summit PT - new resistance bands stocked",
         body="Stocked the treatment rooms with new resistance bands, old ones were getting worn out. FYI only.",
         to="therapists@summitpt.com", from_addr="office-manager@summitpt.com",
         true_category="Work", true_priority=0.13, true_bucket="low"),
    dict(id="T4-W-L4", subject="Highline Motors - showroom floor waxed",
         body="Showroom floor got waxed last night, looks great. No action needed, just wanted the team to know.",
         to="sales-team@highlinemotors.com", from_addr="manager@highlinemotors.com",
         true_category="Work", true_priority=0.12, true_bucket="low"),
    dict(id="T4-W-L5", subject="Evergreen Events - vendor binder updated",
         body="Updated the vendor contact binder with a few new caterers we liked recently, nothing else needed.",
         to="planners@evergreenevents.com", from_addr="lead-planner@evergreenevents.com",
         true_category="Work", true_priority=0.16, true_bucket="low"),
    dict(id="T4-W-L6", subject="Ironwood Tattoo - new flash sheets posted",
         body="Posted a batch of new flash designs on the wall and Instagram, no action needed, just sharing.",
         to="artists@ironwoodtattoo.com", from_addr="shop-owner@ironwoodtattoo.com",
         true_category="Work", true_priority=0.15, true_bucket="low"),
    dict(id="T4-W-L7", subject="Second Chance Shelter - kennel deep clean done",
         body="Finished the deep clean on the north kennel row, smells much better in there now. Nothing further needed.",
         to="staff@secondchanceshelter.org", from_addr="director@secondchanceshelter.org",
         true_category="Work", true_priority=0.14, true_bucket="low"),
    dict(id="T4-W-L8", subject="Verity QA - test environment refreshed",
         body="Refreshed the staging test environment overnight, all good to use whenever anyone needs it.",
         to="testers@verityqa.com", from_addr="lead@verityqa.com",
         true_category="Work", true_priority=0.13, true_bucket="low"),
    dict(id="T4-W-L9", subject="Harvest Table - new farm delivery arrived",
         body="This week's produce delivery from the farm looks great, especially the squash. Just wanted to share.",
         to="kitchen@harvesttable.com", from_addr="chef@harvesttable.com",
         true_category="Work", true_priority=0.15, true_bucket="low"),
    dict(id="T4-W-L10", subject="Lumen Photography - backup drives organized",
         body="Organized the backup drives by shoot date, should make finding old sessions easier going forward.",
         to="photographers@lumenphoto.com", from_addr="studio-manager@lumenphoto.com",
         true_category="Work", true_priority=0.14, true_bucket="low"),
    dict(id="T4-W-L11", subject="nice work on the release",
         body="just wanted to say the last release went out clean, no issues reported, nice work everyone, no reply needed",
         to="testers@verityqa.com", from_addr="lead@verityqa.com",
         true_category="Work", true_priority=0.15, true_bucket="low"),

    # ── Work - medium (11) ───────────────────────────────────────────────
    dict(id="T4-W-M1", subject="Need your notes on the client's revised floor plan",
         body="Could you review the client's revised floor plan sometime this week? Want feedback before we present next round.",
         to="architect@meridianarch.com", from_addr="principal@meridianarch.com",
         true_category="Work", true_priority=0.40, true_bucket="medium"),
    dict(id="T4-W-M2", subject="Need the keg order finalized",
         body="Could you finalize this week's keg order sometime today or tomorrow? Want it in before the weekend rush.",
         to="taproom-manager@copperlinebrewing.com", from_addr="brewmaster@copperlinebrewing.com",
         true_category="Work", true_priority=0.42, true_bucket="medium"),
    dict(id="T4-W-M3", subject="Need the patient reschedule handled",
         body="A patient needs to reschedule their series of sessions, could you sort that out sometime this week?",
         to="office-manager@summitpt.com", from_addr="therapist@summitpt.com",
         true_category="Work", true_priority=0.36, true_bucket="medium"),
    dict(id="T4-W-M4", subject="Need the trade-in appraisal done",
         body="Could you get the trade-in appraisal done sometime this week? Customer's waiting to move forward on the deal.",
         to="sales-team@highlinemotors.com", from_addr="manager@highlinemotors.com",
         true_category="Work", true_priority=0.41, true_bucket="medium"),
    dict(id="T4-W-M5", subject="Need the seating chart approved",
         body="Could you approve the seating chart sometime this week? Caterer needs final numbers soon.",
         to="lead-planner@evergreenevents.com", from_addr="assistant@evergreenevents.com",
         true_category="Work", true_priority=0.39, true_bucket="medium"),
    dict(id="T4-W-M6", subject="Need the consent form signed for tomorrow",
         body="Could you make sure the client signs the updated consent form sometime before tomorrow's appointment?",
         to="artists@ironwoodtattoo.com", from_addr="shop-owner@ironwoodtattoo.com",
         true_category="Work", true_priority=0.43, true_bucket="medium"),
    dict(id="T4-W-M7", subject="Need the adoption paperwork reviewed",
         body="Could you review the adoption paperwork for the Hendersons sometime this week? Want to move forward soon if it looks good.",
         to="staff@secondchanceshelter.org", from_addr="director@secondchanceshelter.org",
         true_category="Work", true_priority=0.37, true_bucket="medium"),
    dict(id="T4-W-M8", subject="Need the regression suite results",
         body="Could you send over the regression suite results sometime this week? Need them before we can sign off on release.",
         to="lead@verityqa.com", from_addr="engineer@verityqa.com",
         true_category="Work", true_priority=0.40, true_bucket="medium"),
    dict(id="T4-W-M9", subject="Need the new menu pricing reviewed",
         body="Could you review the new menu pricing sometime this week? Want to roll it out before next month.",
         to="chef@harvesttable.com", from_addr="owner@harvesttable.com",
         true_category="Work", true_priority=0.38, true_bucket="medium"),
    dict(id="T4-W-M10", subject="Need the wedding album proofs approved",
         body="Could you approve the wedding album proofs sometime this week? Want to send them to print soon.",
         to="photographers@lumenphoto.com", from_addr="studio-manager@lumenphoto.com",
         true_category="Work", true_priority=0.35, true_bucket="medium"),
    dict(id="T4-W-M11", subject="need input on the new hire schedule",
         body="could you look over the new hire's training schedule sometime this week? want to get it locked in soon",
         to="office-manager@summitpt.com", from_addr="therapist@summitpt.com",
         true_category="Work", true_priority=0.38, true_bucket="medium"),

    # ── Work - high (12) ─────────────────────────────────────────────────
    dict(id="T4-W-H1", subject="Client's building has a structural issue we flagged",
         body="Inspectors found a structural issue at the site that needs an emergency review, need you on a call with the engineer right now.",
         to="principal@meridianarch.com", from_addr="architect@meridianarch.com",
         true_category="Work", true_priority=0.90, true_bucket="high"),
    dict(id="T4-W-H2", subject="CO2 leak in the cellar",
         body="We're getting a CO2 leak alarm in the cellar, everyone needs to clear the area immediately and call the gas supplier.",
         to="taproom-manager@copperlinebrewing.com", from_addr="brewmaster@copperlinebrewing.com",
         true_category="Work", true_priority=0.97, true_bucket="high"),
    dict(id="T4-W-H3", subject="Patient fell during the session, needs help now",
         body="A patient just fell hard during their session and can't get up, need help and possibly 911 right now.",
         to="office-manager@summitpt.com", from_addr="therapist@summitpt.com",
         true_category="Work", true_priority=0.98, true_bucket="high"),
    dict(id="T4-W-H4", subject="Customer is threatening legal action right now",
         body="A customer is in the showroom right now threatening legal action over the deal, need a manager out here immediately.",
         to="manager@highlinemotors.com", from_addr="sales-team@highlinemotors.com",
         true_category="Work", true_priority=0.83, true_bucket="high"),
    dict(id="T4-W-H5", subject="Venue just cancelled on us, wedding is Saturday",
         body="The venue just cancelled on us and the wedding is this Saturday, need everyone brainstorming backups right now.",
         to="lead-planner@evergreenevents.com", from_addr="assistant@evergreenevents.com",
         true_category="Work", true_priority=0.92, true_bucket="high"),
    dict(id="T4-W-H6", subject="Client is having an allergic reaction to the ink",
         body="A client is having a reaction right now during their session, need you back here immediately.",
         to="shop-owner@ironwoodtattoo.com", from_addr="artists@ironwoodtattoo.com",
         true_category="Work", true_priority=0.96, true_bucket="high"),
    dict(id="T4-W-H7", subject="Dog got loose and is running toward the road",
         body="One of the shelter dogs just got loose and is heading toward the road, need everyone out here right now.",
         to="staff@secondchanceshelter.org", from_addr="director@secondchanceshelter.org",
         true_category="Work", true_priority=0.89, true_bucket="high"),
    dict(id="T4-W-H8", subject="Critical bug found in production, deploying now",
         body="We just found a critical bug live in production affecting all users, need everyone on the incident bridge immediately.",
         to="lead@verityqa.com", from_addr="engineer@verityqa.com",
         true_category="Work", true_priority=0.95, true_bucket="high"),
    dict(id="T4-W-H9", subject="Health inspector is here right now, unannounced",
         body="The health inspector just walked in for an unannounced visit, need you here immediately, kitchen needs to be perfect now.",
         to="owner@harvesttable.com", from_addr="chef@harvesttable.com",
         true_category="Work", true_priority=0.85, true_bucket="high"),
    dict(id="T4-W-H10", subject="Backup drive with the wedding shoot just failed",
         body="The only backup of Saturday's wedding shoot just failed and won't mount, need help recovering it immediately, client picks up the album Friday.",
         to="studio-manager@lumenphoto.com", from_addr="photographers@lumenphoto.com",
         true_category="Work", true_priority=0.84, true_bucket="high"),
    dict(id="T4-W-H11", subject="get out here now",
         body="get out here right now, the dog is near the road, hurry",
         to="staff@secondchanceshelter.org", from_addr="director@secondchanceshelter.org",
         true_category="Work", true_priority=0.90, true_bucket="high"),
    dict(id="T4-W-H12", subject="call me now",
         body="call me the second you see this, we have a structural problem and need the engineer on the phone now",
         to="principal@meridianarch.com", from_addr="architect@meridianarch.com",
         true_category="Work", true_priority=0.88, true_bucket="high"),

    # ── Personal - low (11) ──────────────────────────────────────────────
    dict(id="T4-P-L1", subject="work bestie update - nothing new just checking in",
         body="Nothing new really, just wanted to say hi since we haven't talked outside work in a while. No need to respond fast.",
         to="workbestie@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.14, true_bucket="low"),
    dict(id="T4-P-L2", subject="sister-in-law's garden update",
         body="Your tomatoes in the community garden are doing great, walked by today and had to tell you.",
         to="sil@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.15, true_bucket="low"),
    dict(id="T4-P-L3", subject="old coach would be proud",
         body="Ran into someone from the old team today and it made me think of you, thought I'd share the memory.",
         to="oldcoach@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.13, true_bucket="low"),
    dict(id="T4-P-L4", subject="miss our calls",
         body="Been a minute since we caught up, miss our long calls, no rush to respond, just thinking of you.",
         to="longdistancepartner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.17, true_bucket="low"),
    dict(id="T4-P-L5", subject="twin telepathy strikes again",
         body="Was literally just thinking about you and then saw your post, twin telepathy is real I swear.",
         to="twin@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.14, true_bucket="low"),
    dict(id="T4-P-L6", subject="neighbor's new garden gnome",
         body="Our elderly neighbor put up the funniest garden gnome collection, made my whole walk today, thought you'd laugh.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.12, true_bucket="low"),
    dict(id="T4-P-L7", subject="church potluck was great",
         body="The potluck after service was really nice today, missed seeing you there, hope to catch you next time.",
         to="churchfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.15, true_bucket="low"),
    dict(id="T4-P-L8", subject="loved this month's pick",
         body="Really enjoyed this month's book, can't wait to hear everyone's thoughts at the next meeting.",
         to="bookclubmember@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.16, true_bucket="low"),
    dict(id="T4-P-L9", subject="gg last night",
         body="gg last night, that last match was intense, still thinking about that clutch play you made",
         to="gamingfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.11, true_bucket="low"),
    dict(id="T4-P-L10", subject="the cat missed you",
         body="The cat kept looking for you the whole time you were pet-sitting for us, she clearly misses you already, thanks again.",
         to="petsitterfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.13, true_bucket="low"),
    dict(id="T4-P-L11", subject="lol check this out",
         body="lol found the weirdest thing at the thrift store today, had to send you a picture, no reply needed",
         to="workbestie@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.12, true_bucket="low"),

    # ── Personal - medium (11) ───────────────────────────────────────────
    dict(id="T4-P-M1", subject="need to plan the visit soon",
         body="Trying to plan when I'll visit next, are you free the week of the 15th? Need to know soon to book the flight.",
         to="longdistancepartner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.41, true_bucket="medium"),
    dict(id="T4-P-M2", subject="need you to confirm the reunion date",
         body="We're trying to pick a date for the twin reunion trip, can you confirm which weekend works by this week?",
         to="twin@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.36, true_bucket="medium"),
    dict(id="T4-P-M3", subject="can you cover the pet sitting next week?",
         body="Need someone to watch the cat next week, are you available? Let me know soon so I can ask someone else if not.",
         to="petsitterfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.39, true_bucket="medium"),
    dict(id="T4-P-M4", subject="need the group's decision on the gaming trip",
         body="Need to know by this weekend if you're coming to the convention, hotel block closes soon.",
         to="gamingfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.37, true_bucket="medium"),
    dict(id="T4-P-M5", subject="can we talk about the family reunion",
         body="We should figure out reunion logistics soon, are you free to hop on a call sometime this week?",
         to="sil@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.38, true_bucket="medium"),
    dict(id="T4-P-M6", subject="need advice before I decide",
         body="Have to make a decision about the job offer soon, could we talk sometime this week? Your advice always helps.",
         to="oldcoach@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.42, true_bucket="medium"),
    dict(id="T4-P-M7", subject="need to reschedule our coffee catch-up",
         body="Something came up, can we move our coffee date to next week? Let me know what day works for you.",
         to="workbestie@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.30, true_bucket="medium"),
    dict(id="T4-P-M8", subject="need your answer on the potluck dish",
         body="Signing up dishes for next week's potluck, can you let me know what you're bringing sometime soon?",
         to="churchfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.28, true_bucket="medium"),
    dict(id="T4-P-M9", subject="need you to pick the next book soon",
         body="It's your turn to pick next month's book, could you let everyone know your choice sometime this week?",
         to="bookclubmember@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.29, true_bucket="medium"),
    dict(id="T4-P-M10", subject="need to talk about visiting mom together",
         body="Thinking we should visit mom together sometime soon, are you free to plan a weekend this month?",
         to="sil@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.40, true_bucket="medium"),
    dict(id="T4-P-M11", subject="need an answer before I book",
         body="hey, flights are filling up, need to know if you can make the visit work by end of week",
         to="longdistancepartner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.43, true_bucket="medium"),

    # ── Personal - high (12) ─────────────────────────────────────────────
    dict(id="T4-P-H1", subject="twin, something's wrong, call me",
         body="Something feels really wrong and I don't know why, please call me the second you see this.",
         to="twin@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.90, true_bucket="high"),
    dict(id="T4-P-H2", subject="long distance emergency, need you",
         body="Something happened here and I really need to hear your voice right now, please call as soon as you can.",
         to="longdistancepartner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.84, true_bucket="high"),
    dict(id="T4-P-H3", subject="old coach, need help, dad's in the hospital",
         body="Dad's in the hospital and I don't know what to do, could really use your advice, please call when you can today.",
         to="oldcoach@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.82, true_bucket="high"),
    dict(id="T4-P-H4", subject="church friend, urgent prayer request",
         body="Something serious just happened in our family, need people praying and need to talk to someone, can you call me right now.",
         to="churchfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.79, true_bucket="high"),
    dict(id="T4-P-H5", subject="workbestie, I think I'm getting fired, need advice now",
         body="I think I'm about to get let go in the next hour and I'm panicking, can you call me right now, I need advice fast.",
         to="workbestie@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.72, true_bucket="high"),
    dict(id="T4-P-H6", subject="cat is having a seizure",
         body="The cat you're watching just had what looked like a seizure, I'm calling the emergency vet now, need you to stay calm and watch her.",
         to="petsitterfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.93, true_bucket="high"),
    dict(id="T4-P-H7", subject="sister-in-law, mom fell at your place",
         body="Mom just fell at your house, is she okay, please call me the second you see this.",
         to="sil@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.97, true_bucket="high"),
    dict(id="T4-P-H8", subject="gaming friend, need to talk right now",
         body="Not about gaming, something's really wrong and I don't have anyone else to talk to right now, can you call?",
         to="gamingfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.76, true_bucket="high"),
    dict(id="T4-P-H9", subject="book club friend, need you right now",
         body="I know this is random but I really need someone right now, can you call me as soon as you see this.",
         to="bookclubmember@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.74, true_bucket="high"),
    dict(id="T4-P-H10", subject="call me now",
         body="please call me right now, something happened, i need to talk to someone",
         to="workbestie@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.80, true_bucket="high"),
    dict(id="T4-P-H11", subject="911 sil",
         body="mom fell hard, calling 911, please come now",
         to="sil@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.98, true_bucket="high"),
    dict(id="T4-P-H12", subject="need you",
         body="please pick up, need you right now, it's bad",
         to="twin@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.89, true_bucket="high"),

    # ── Other - low (12) ─────────────────────────────────────────────────
    dict(id="T4-O-L1", subject="City council newsletter - this month's agenda recap",
         body="This month's council meeting recap is up, nothing controversial, mostly routine business.",
         to="residents@fernwoodhoa.org", from_addr="newsletter@citygov.org",
         true_category="Other", true_priority=0.13, true_bucket="low"),
    dict(id="T4-O-L2", subject="School bus route - no changes for next semester",
         body="Just confirming your child's bus route stays the same next semester, no action needed.",
         to="parent@gmail.com", from_addr="transportation@maplegroveschools.org",
         true_category="Other", true_priority=0.14, true_bucket="low"),
    dict(id="T4-O-L3", subject="Apartment complex - pool schedule for the season",
         body="Pool hours for the season are posted, nothing to do, just wanted residents to have the schedule.",
         to="tenants@fernwoodapartments.com", from_addr="management@fernwoodapartments.com",
         true_category="Other", true_priority=0.15, true_bucket="low"),
    dict(id="T4-O-L4", subject="Your credit card statement is ready",
         body="Your monthly statement is available online, nothing unusual on it, just the regular notice.",
         to="cardholder@gmail.com", from_addr="statements@brightpeakcredit.com",
         true_category="Other", true_priority=0.12, true_bucket="low"),
    dict(id="T4-O-L5", subject="Your order from Cartwheel Goods shipped",
         body="Good news, your order shipped today. Tracking link attached, no action needed.",
         to="customer@gmail.com", from_addr="orders@cartwheelgoods.com",
         true_category="Other", true_priority=0.11, true_bucket="low"),
    dict(id="T4-O-L6", subject="Your delivery arrived",
         body="Your food order was delivered, hope you enjoy it, no action needed unless something's wrong.",
         to="customer@gmail.com", from_addr="orders@doorfeastapp.com",
         true_category="Other", true_priority=0.11, true_bucket="low"),
    dict(id="T4-O-L7", subject="New matches this week",
         body="You have a few new matches this week, check them out whenever you're free, no rush.",
         to="user@gmail.com", from_addr="notify@sparkconnect.com",
         true_category="Other", true_priority=0.14, true_bucket="low"),
    dict(id="T4-O-L8", subject="Your social account - login summary",
         body="Here's a summary of your recent logins, all from recognized devices, no action needed.",
         to="user@gmail.com", from_addr="security@snapgridapp.com",
         true_category="Other", true_priority=0.13, true_bucket="low"),
    dict(id="T4-O-L9", subject="Your tax software - filing was accepted",
         body="Your return was accepted, no further action needed, refund timeline is on your dashboard whenever you want to check.",
         to="filer@gmail.com", from_addr="notify@filesimpletax.com",
         true_category="Other", true_priority=0.12, true_bucket="low"),
    dict(id="T4-O-L10", subject="HOA board meeting minutes posted",
         body="Minutes from last week's board meeting are posted, mostly routine items, nothing urgent.",
         to="residents@brookstonehoa.org", from_addr="secretary@brookstonehoa.org",
         true_category="Other", true_priority=0.15, true_bucket="low"),
    dict(id="T4-O-L11", subject="Continuing ed - new class catalog is out",
         body="The new semester catalog for continuing ed classes just came out, browse whenever you're curious.",
         to="alumni@stateuniv.edu", from_addr="continuinged@stateuniv.edu",
         true_category="Other", true_priority=0.16, true_bucket="low"),
    dict(id="T4-O-L12", subject="thanks for your feedback",
         body="thanks for the feedback on your last stay, glad you enjoyed it, hope to host you again sometime",
         to="member@vinecrestwinery.com", from_addr="events@vinecrestwinery.com",
         true_category="Other", true_priority=0.13, true_bucket="low"),

    # ── Other - medium (11) ──────────────────────────────────────────────
    dict(id="T4-O-M1", subject="Please respond about the upcoming council vote",
         body="A zoning change affecting your street is up for vote soon, please review and submit comments within two weeks if you have concerns.",
         to="residents@fernwoodhoa.org", from_addr="clerk@citygov.org",
         true_category="Other", true_priority=0.40, true_bucket="medium"),
    dict(id="T4-O-M2", subject="Please update your child's transportation form",
         body="We need an updated pickup authorization form on file, please submit it within the next couple weeks.",
         to="parent@gmail.com", from_addr="transportation@maplegroveschools.org",
         true_category="Other", true_priority=0.38, true_bucket="medium"),
    dict(id="T4-O-M3", subject="Lease renewal decision needed soon",
         body="Your lease is up for renewal, please let us know your decision within the next two weeks.",
         to="tenants@fernwoodapartments.com", from_addr="management@fernwoodapartments.com",
         true_category="Other", true_priority=0.44, true_bucket="medium"),
    dict(id="T4-O-M4", subject="Please verify a recent charge",
         body="We noticed an unusual but not clearly fraudulent charge, please verify it within the next few days.",
         to="cardholder@gmail.com", from_addr="fraud-review@brightpeakcredit.com",
         true_category="Other", true_priority=0.42, true_bucket="medium"),
    dict(id="T4-O-M5", subject="Item in your order is on backorder",
         body="One item in your recent order is delayed, please choose a substitute or confirm you're okay waiting within a few days.",
         to="customer@gmail.com", from_addr="orders@cartwheelgoods.com",
         true_category="Other", true_priority=0.34, true_bucket="medium"),
    dict(id="T4-O-M6", subject="Please confirm delivery instructions",
         body="Driver had trouble finding your address last time, please confirm updated delivery instructions before your next order.",
         to="customer@gmail.com", from_addr="support@doorfeastapp.com",
         true_category="Other", true_priority=0.31, true_bucket="medium"),
    dict(id="T4-O-M7", subject="Please verify your profile to keep matching",
         body="We need to verify your profile photo to keep showing you matches, please complete verification within the next week.",
         to="user@gmail.com", from_addr="trust@sparkconnect.com",
         true_category="Other", true_priority=0.32, true_bucket="medium"),
    dict(id="T4-O-M8", subject="Please review a new login location",
         body="We noticed a login from a new location, please confirm it was you within the next few days.",
         to="user@gmail.com", from_addr="security@snapgridapp.com",
         true_category="Other", true_priority=0.41, true_bucket="medium"),
    dict(id="T4-O-M9", subject="Additional documentation needed for your return",
         body="We need one more document to finish processing your return, please upload it within the next two weeks.",
         to="filer@gmail.com", from_addr="support@filesimpletax.com",
         true_category="Other", true_priority=0.39, true_bucket="medium"),
    dict(id="T4-O-M10", subject="HOA - please respond about the fence variance",
         body="Your fence variance request needs one more piece of info, please respond within the next couple weeks.",
         to="resident@gmail.com", from_addr="secretary@brookstonehoa.org",
         true_category="Other", true_priority=0.37, true_bucket="medium"),
    dict(id="T4-O-M11", subject="please register before the class fills up",
         body="the continuing ed class you looked at is filling up, please register within the next week if you want a spot",
         to="alumni@stateuniv.edu", from_addr="continuinged@stateuniv.edu",
         true_category="Other", true_priority=0.35, true_bucket="medium"),

    # ── Other - high (9) ─────────────────────────────────────────────────
    dict(id="T4-O-H1", subject="Emergency zoning meeting tonight about your property",
         body="An emergency council session is happening tonight regarding a decision that affects your property, please attend or submit comments today.",
         to="residents@fernwoodhoa.org", from_addr="clerk@citygov.org",
         true_category="Other", true_priority=0.79, true_bucket="high"),
    dict(id="T4-O-H2", subject="School lockdown in effect right now",
         body="The school is currently in a precautionary lockdown, all students are safe, please do not come to the school until further notice.",
         to="parent@gmail.com", from_addr="alerts@maplegroveschools.org",
         true_category="Other", true_priority=0.99, true_bucket="high"),
    dict(id="T4-O-H3", subject="Fire alarm active in your building right now",
         body="A fire alarm is currently active in your building, please evacuate immediately using the nearest exit.",
         to="tenants@fernwoodapartments.com", from_addr="management@fernwoodapartments.com",
         true_category="Other", true_priority=0.99, true_bucket="high"),
    dict(id="T4-O-H4", subject="Your card was just used for a large purchase abroad",
         body="A large purchase was just attempted on your card from another country, if this wasn't you call us immediately to block it.",
         to="cardholder@gmail.com", from_addr="fraud@brightpeakcredit.com",
         true_category="Other", true_priority=0.90, true_bucket="high"),
    dict(id="T4-O-H5", subject="Recall - stop using the product immediately",
         body="The item you purchased has been recalled for a fire risk, please stop using it immediately and follow the return instructions.",
         to="customer@gmail.com", from_addr="recalls@cartwheelgoods.com",
         true_category="Other", true_priority=0.86, true_bucket="high"),
    dict(id="T4-O-H6", subject="Your account is being accessed right now from an unknown device",
         body="Someone is logged into your account right now from a device we don't recognize, please secure your account immediately.",
         to="user@gmail.com", from_addr="security@snapgridapp.com",
         true_category="Other", true_priority=0.91, true_bucket="high"),
    dict(id="T4-O-H7", subject="Filing deadline is today, action required now",
         body="We noticed your return hasn't been submitted and the deadline is today, please finish filing immediately to avoid penalties.",
         to="filer@gmail.com", from_addr="alerts@filesimpletax.com",
         true_category="Other", true_priority=0.82, true_bucket="high"),
    dict(id="T4-O-H8", subject="urgent - water main break flooding the parking lot",
         body="a water main just broke and is flooding the parking lot fast, please move your car immediately if it's parked there",
         to="tenants@fernwoodapartments.com", from_addr="management@fernwoodapartments.com",
         true_category="Other", true_priority=0.88, true_bucket="high"),
    dict(id="T4-O-H9", subject="call now about a safety concern",
         body="a safety concern was just reported involving your account, please call us immediately to verify your identity",
         to="user@gmail.com", from_addr="trust@sparkconnect.com",
         true_category="Other", true_priority=0.78, true_bucket="high"),
]

assert len(ROWS) == 100, f"expected 100, got {len(ROWS)}"
