"""
synthetic_priority_train_batch1.py
────────────────────────────────────
Batch 1/5 of hand-authored synthetic TRAINING rows (distinct from
adversarial_test_set.py, which stays held-out for eval — no overlap in
scenario/wording between the two). Purpose: item 3e in PROJECT_STATUS.md
found the trained priority model collapses out-of-distribution because its
504 training rows are 100% one 2001 corporate-Enron register. These rows
inject the specific missing registers: modern personal/casual/texting
correspondence, non-Enron business domains (health, education, retail,
law, nonprofit, manufacturing, hospitality), and genuine safety/emergency
language — while a companion effort (see PROJECT_STATUS item 3e/3f)
evaluates whether adding them actually moves the out-of-distribution
accuracy, not just same-corpus CV.

Fields: id, subject, body, to, from_addr, true_category (Work/Personal/
Other), true_priority (continuous 0.1-1.0), true_bucket (low/medium/high
via the same bucket() cutoffs as gold_priority_labeled.csv: <0.35 low,
<0.55 medium, else high).
"""

ROWS = [
    # ── Work - low (11) ──────────────────────────────────────────────────
    dict(id="T1-W-L1", subject="Notes from the Alderleaf Health onboarding call",
         body="Sharing notes from this morning's onboarding call for the new EHR vendor. Nothing needs action, just archiving for reference.",
         to="team@alderleafhealth.com", from_addr="ops@alderleafhealth.com",
         true_category="Work", true_priority=0.18, true_bucket="low"),
    dict(id="T1-W-L2", subject="Menu update for next month - Union Street Cafe",
         body="Rotating in a couple new seasonal items next month, chef will share the tasting schedule when it's ready. No rush on anything from your end.",
         to="staff@unionstreetcafe.com", from_addr="manager@unionstreetcafe.com",
         true_category="Work", true_priority=0.16, true_bucket="low"),
    dict(id="T1-W-L3", subject="Fenwick & Cole - library subscription renewed",
         body="Just confirming the legal research database subscription auto-renewed for another year. No action needed on anyone's part.",
         to="attorneys@fenwickcole.com", from_addr="admin@fenwickcole.com",
         true_category="Work", true_priority=0.14, true_bucket="low"),
    dict(id="T1-W-L4", subject="Great turnout at the open house",
         body="Just wanted to say the open house went really well yesterday, lots of good feedback from families. Thanks everyone for helping out.",
         to="staff@maplegroveschools.org", from_addr="principal@maplegroveschools.org",
         true_category="Work", true_priority=0.15, true_bucket="low"),
    dict(id="T1-W-L5", subject="Ferro Manufacturing - shift schedule for next month posted",
         body="Next month's shift schedule is posted on the board and in the portal. Same rotation as usual, nothing's changed.",
         to="floor-staff@ferromfg.com", from_addr="scheduling@ferromfg.com",
         true_category="Work", true_priority=0.17, true_bucket="low"),
    dict(id="T1-W-L6", subject="Cascade Nonprofit Alliance - volunteer thank you",
         body="Wanted to send a quick thank you to everyone who volunteered at the food drive this weekend, it made a real difference. No reply needed.",
         to="volunteers@cascadealliance.org", from_addr="coordinator@cascadealliance.org",
         true_category="Work", true_priority=0.13, true_bucket="low"),
    dict(id="T1-W-L7", subject="Solstice Robotics - lab cleaned and restocked",
         body="FYI the materials lab was restocked and cleaned over the weekend, should be good to go for whenever you need it next.",
         to="rd-team@solsticerobotics.com", from_addr="facilities@solsticerobotics.com",
         true_category="Work", true_priority=0.16, true_bucket="low"),
    dict(id="T1-W-L8", subject="Larkspur Realty - new listing photos are in",
         body="Photos from the shoot on Elm Street came back, they're in the shared drive whenever you want to take a look.",
         to="agents@larkspurrealty.com", from_addr="marketing@larkspurrealty.com",
         true_category="Work", true_priority=0.19, true_bucket="low"),
    dict(id="T1-W-L9", subject="Nimbus Retail - Q2 sales recap deck",
         body="Attaching the Q2 recap deck for anyone who wants to reference it, nothing new here that wasn't in the meeting.",
         to="regional-managers@nimbusretail.com", from_addr="analytics@nimbusretail.com",
         true_category="Work", true_priority=0.18, true_bucket="low"),
    dict(id="T1-W-L10", subject="BrightPath Consulting - office plants watered",
         body="Just a heads up the office plant service came by today, everything's set for the next few weeks.",
         to="office@brightpathconsulting.com", from_addr="admin@brightpathconsulting.com",
         true_category="Work", true_priority=0.12, true_bucket="low"),
    dict(id="T1-W-L11", subject="nice work on the demo",
         body="hey, just wanted to say the client demo yesterday went really smoothly, good job. no need to reply, just wanted you to know.",
         to="dev@solsticerobotics.com", from_addr="teamlead@solsticerobotics.com",
         true_category="Work", true_priority=0.16, true_bucket="low"),

    # ── Work - medium (11) ───────────────────────────────────────────────
    dict(id="T1-W-M1", subject="Can you review the intake form draft?",
         body="Whenever you get a chance this week, could you take a look at the new patient intake form draft and flag anything unclear?",
         to="nurse.lead@alderleafhealth.com", from_addr="admin@alderleafhealth.com",
         true_category="Work", true_priority=0.40, true_bucket="medium"),
    dict(id="T1-W-M2", subject="Need your sign-off on the catering order by Wednesday",
         body="We need to place the catering order for the fundraiser by Wednesday, can you approve the final headcount before then?",
         to="events@cascadealliance.org", from_addr="coordinator@cascadealliance.org",
         true_category="Work", true_priority=0.44, true_bucket="medium"),
    dict(id="T1-W-M3", subject="Please confirm your availability for the site visit",
         body="Can you confirm if you're available for the client site visit next week? Need to lock in the schedule soon.",
         to="engineer@ferromfg.com", from_addr="pm@ferromfg.com",
         true_category="Work", true_priority=0.42, true_bucket="medium"),
    dict(id="T1-W-M4", subject="Parent conference sign-ups need review",
         body="Could you look over the parent-teacher conference sign-up sheet this week and let me know if any time slots need adjusting?",
         to="teacher@maplegroveschools.org", from_addr="office@maplegroveschools.org",
         true_category="Work", true_priority=0.39, true_bucket="medium"),
    dict(id="T1-W-M5", subject="Draft contract for the Elm Street listing",
         body="Attached the draft listing agreement, could you review and send comments back sometime before Friday's meeting?",
         to="broker@larkspurrealty.com", from_addr="agent@larkspurrealty.com",
         true_category="Work", true_priority=0.41, true_bucket="medium"),
    dict(id="T1-W-M6", subject="Following up on the vendor comparison",
         body="Circling back on the vendor comparison spreadsheet - any chance you can finish your section by end of week?",
         to="procurement@brightpathconsulting.com", from_addr="lead@brightpathconsulting.com",
         true_category="Work", true_priority=0.43, true_bucket="medium"),
    dict(id="T1-W-M7", subject="Need input on the store layout change",
         body="We're planning to shift the front-of-store layout next month, could use your input before we finalize, no huge rush but soon would help.",
         to="store-manager@nimbusretail.com", from_addr="regional@nimbusretail.com",
         true_category="Work", true_priority=0.38, true_bucket="medium"),
    dict(id="T1-W-M8", subject="Please review the associate's draft brief",
         body="Could you review the draft brief before it goes to the client on Thursday? Want your notes in the next couple days.",
         to="partner@fenwickcole.com", from_addr="associate@fenwickcole.com",
         true_category="Work", true_priority=0.45, true_bucket="medium"),
    dict(id="T1-W-M9", subject="Reminder: submit your firmware test results",
         body="Just following up - could you send over the firmware test results sometime this week? Need them before we move to the next sprint.",
         to="qa@solsticerobotics.com", from_addr="lead@solsticerobotics.com",
         true_category="Work", true_priority=0.40, true_bucket="medium"),
    dict(id="T1-W-M10", subject="Shift swap request - need approval",
         body="Could you approve my shift swap for next Tuesday when you get a chance? Trying to confirm with the other person soon.",
         to="scheduling@ferromfg.com", from_addr="employee@ferromfg.com",
         true_category="Work", true_priority=0.37, true_bucket="medium"),
    dict(id="T1-W-M11", subject="need your notes on the grant application",
         body="hey, could you send over your section of the grant application sometime this week? deadline to submit internally is coming up soon-ish.",
         to="grants@cascadealliance.org", from_addr="writer@cascadealliance.org",
         true_category="Work", true_priority=0.42, true_bucket="medium"),

    # ── Work - high (12) ─────────────────────────────────────────────────
    dict(id="T1-W-H1", subject="Patient transfer needs approval right now",
         body="We have a patient who needs to be transferred immediately, I need your sign-off on the transfer paperwork in the next few minutes.",
         to="dr.chen@alderleafhealth.com", from_addr="charge.nurse@alderleafhealth.com",
         true_category="Work", true_priority=0.90, true_bucket="high"),
    dict(id="T1-W-H2", subject="Kitchen fire suppression system went off",
         body="The fire suppression system just triggered in the kitchen, everyone's out safely but we need the fire department contact and the owner on the phone now.",
         to="owner@unionstreetcafe.com", from_addr="manager@unionstreetcafe.com",
         true_category="Work", true_priority=0.93, true_bucket="high"),
    dict(id="T1-W-H3", subject="Court filing window closes at 5pm today",
         body="We cannot miss the filing window today, it closes at 5pm. I need the signed affidavit back from you within the hour.",
         to="associate@fenwickcole.com", from_addr="partner@fenwickcole.com",
         true_category="Work", true_priority=0.92, true_bucket="high"),
    dict(id="T1-W-H4", subject="Student went missing during the field trip",
         body="One of the students isn't with the group and we can't locate them, we need the school office to call the parents immediately.",
         to="office@maplegroveschools.org", from_addr="teacher@maplegroveschools.org",
         true_category="Work", true_priority=0.95, true_bucket="high"),
    dict(id="T1-W-H5", subject="Buyer wants to withdraw the offer today",
         body="The buyer is threatening to pull out of the deal today unless we get the inspection report to them in the next hour. Need your help now.",
         to="broker@larkspurrealty.com", from_addr="agent@larkspurrealty.com",
         true_category="Work", true_priority=0.85, true_bucket="high"),
    dict(id="T1-W-H6", subject="Client is furious, needs a call in the next 15 minutes",
         body="The client just called extremely upset about the missed milestone, they want someone on the phone in the next 15 minutes or they're pulling the contract.",
         to="account-lead@brightpathconsulting.com", from_addr="associate@brightpathconsulting.com",
         true_category="Work", true_priority=0.88, true_bucket="high"),
    dict(id="T1-W-H7", subject="POS system is down at all three stores",
         body="All three registers are down company-wide right now, customers can't check out. Need IT on this immediately.",
         to="it@nimbusretail.com", from_addr="ops@nimbusretail.com",
         true_category="Work", true_priority=0.91, true_bucket="high"),
    dict(id="T1-W-H8", subject="Someone's hand is caught in the press",
         body="There's been an accident on the floor, someone's hand is caught in the press. Call 911 and get maintenance down here right now.",
         to="safety@ferromfg.com", from_addr="floor-supervisor@ferromfg.com",
         true_category="Work", true_priority=0.98, true_bucket="high"),
    dict(id="T1-W-H9", subject="Robot arm malfunctioned during the live customer demo",
         body="The robot arm just malfunctioned mid-demo in front of the client, need an engineer on the call right now before they walk.",
         to="engineering@solsticerobotics.com", from_addr="sales@solsticerobotics.com",
         true_category="Work", true_priority=0.83, true_bucket="high"),
    dict(id="T1-W-H10", subject="Grant deadline moved up to tonight",
         body="Just heard the funder moved the deadline up to tonight at midnight instead of next week. We need the final draft from you within the next few hours.",
         to="writer@cascadealliance.org", from_addr="director@cascadealliance.org",
         true_category="Work", true_priority=0.87, true_bucket="high"),
    dict(id="T1-W-H11", subject="need this now",
         body="need the signed release from you in the next ten minutes or we miss the broadcast window, please call me",
         to="associate@fenwickcole.com", from_addr="partner@fenwickcole.com",
         true_category="Work", true_priority=0.86, true_bucket="high"),
    dict(id="T1-W-H12", subject="911",
         body="come to the loading dock now, forklift tipped over",
         to="safety@ferromfg.com", from_addr="floor-supervisor@ferromfg.com",
         true_category="Work", true_priority=0.97, true_bucket="high"),

    # ── Personal - low (11) ──────────────────────────────────────────────
    dict(id="T1-P-L1", subject="found this old photo",
         body="Was cleaning out a drawer and found this old photo of us from high school, thought you'd get a kick out of it. No need to respond.",
         to="jess.friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.14, true_bucket="low"),
    dict(id="T1-P-L2", subject="grandma's cookie recipe",
         body="Finally typed up grandma's cookie recipe like you asked, attaching it here. No rush trying it out.",
         to="cousin@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.15, true_bucket="low"),
    dict(id="T1-P-L3", subject="how was the concert",
         body="Saw your story from the concert last night, looked like a blast! Tell me about it whenever, no rush.",
         to="roommate@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.13, true_bucket="low"),
    dict(id="T1-P-L4", subject="new plant on the windowsill",
         body="Got a new plant for the kitchen windowsill, it's doing surprisingly well so far. Thought I'd share since you always ask about my plants.",
         to="bestfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.12, true_bucket="low"),
    dict(id="T1-P-L5", subject="that show you recommended",
         body="Finally started the show you told me about months ago, really into it now, thanks for the rec. No response needed.",
         to="partner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.16, true_bucket="low"),
    dict(id="T1-P-L6", subject="sunday morning walk",
         body="Went on a nice long walk this morning, weather was perfect, made me think of our old Sunday routine. Miss those.",
         to="sister@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.15, true_bucket="low"),
    dict(id="T1-P-L7", subject="random question",
         body="Random, but do you remember the name of that little diner we used to go to as kids? Trying to remember for no real reason.",
         to="brother@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.17, true_bucket="low"),
    dict(id="T1-P-L8", subject="lol you have to see this",
         body="lol my cat just knocked an entire plant off the shelf, sending you the video, no context needed just enjoy",
         to="bestfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.11, true_bucket="low"),
    dict(id="T1-P-L9", subject="thinking of grandpa today",
         body="Just been thinking about grandpa a lot today, no particular reason, wanted to share that with someone who'd understand.",
         to="uncle@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.18, true_bucket="low"),
    dict(id="T1-P-L10", subject="new haircut",
         body="Got a haircut today, feeling good about it, attaching a picture because why not. No need to respond, just wanted to share.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.13, true_bucket="low"),
    dict(id="T1-P-L11", subject="miss you",
         body="hey just thinking about you today, hope things are good over there, no need to write back right away",
         to="collegefriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.14, true_bucket="low"),

    # ── Personal - medium (11) ───────────────────────────────────────────
    dict(id="T1-P-M1", subject="can you watch the dog next weekend?",
         body="Would you be able to watch the dog next weekend while we're out of town? Let me know soon so I can figure out a backup if not.",
         to="neighbor@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.41, true_bucket="medium"),
    dict(id="T1-P-M2", subject="need to figure out thanksgiving",
         body="We should figure out Thanksgiving plans soon, are you hosting again this year or should we? Would help to know in the next week or two.",
         to="sister@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.38, true_bucket="medium"),
    dict(id="T1-P-M3", subject="rent split for next month",
         body="Can we sort out the rent split before the end of the month? Want to make sure we're both clear before it's due.",
         to="roommate@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.44, true_bucket="medium"),
    dict(id="T1-P-M4", subject="can you send the group photo?",
         body="Could you send me the group photo from the reunion when you get a chance? Want to get prints made before the holidays.",
         to="cousin@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.36, true_bucket="medium"),
    dict(id="T1-P-M5", subject="need to talk about the lease",
         body="We should talk about whether we're renewing the lease, landlord wants an answer in the next couple weeks. Can we grab coffee this week to discuss?",
         to="partner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.43, true_bucket="medium"),
    dict(id="T1-P-M6", subject="borrowing the car this weekend?",
         body="Any chance I could borrow your car this weekend? Mine's in the shop. Let me know soon so I can make other plans if not.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.39, true_bucket="medium"),
    dict(id="T1-P-M7", subject="mom's doctor appointment - can you come?",
         body="Mom has a follow-up appointment next week and I think it'd help to have both of us there, are you free that day?",
         to="brother@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.45, true_bucket="medium"),
    dict(id="T1-P-M8", subject="wedding RSVP - need your answer soon",
         body="Hey, we need final headcounts for the caterer soon, can you send your RSVP this week? No worries either way, just need to know.",
         to="collegefriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.42, true_bucket="medium"),
    dict(id="T1-P-M9", subject="can we reschedule game night",
         body="Something came up, can we move game night to next week instead? Let me know what day works for everyone.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.34, true_bucket="medium"),
    dict(id="T1-P-M10", subject="need a favor before I move",
         body="I'm moving in a couple weeks and could really use a hand packing up the garage sometime before then, any chance you're free one of these days?",
         to="bestfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.40, true_bucket="medium"),
    dict(id="T1-P-M11", subject="need an answer on the trip soon",
         body="hey, flights are getting more expensive, need to know if you're in for the trip by this weekend so I can book",
         to="collegefriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.43, true_bucket="medium"),

    # ── Personal - high (12) ─────────────────────────────────────────────
    dict(id="T1-P-H1", subject="mom fell, we're at the ER",
         body="Mom fell down the stairs, we're at the ER right now, please call me as soon as you get this.",
         to="sibling@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.96, true_bucket="high"),
    dict(id="T1-P-H2", subject="the baby's fever won't go down",
         body="The baby's fever is at 104 and not coming down with medicine, we're heading to urgent care, please call me the second you see this.",
         to="partner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.97, true_bucket="high"),
    dict(id="T1-P-H3", subject="pipe burst in the basement",
         body="A pipe just burst in the basement and it's flooding fast, I need help right now, can you come over immediately.",
         to="neighbor@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.88, true_bucket="high"),
    dict(id="T1-P-H4", subject="grandpa is in the hospital",
         body="Grandpa was taken to the hospital this morning, doctors are running tests now, will update as soon as I know more, please call when you can.",
         to="cousin@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.90, true_bucket="high"),
    dict(id="T1-P-H5", subject="lost my wallet and keys, locked out",
         body="I lost my wallet and keys somewhere downtown and I'm locked out of the apartment, can you come let me in right now?",
         to="roommate@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.75, true_bucket="high"),
    dict(id="T1-P-H6", subject="dog got out and ran off",
         body="The dog just got out through the fence and took off down the street, I need help looking for him right now.",
         to="neighbor@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.82, true_bucket="high"),
    dict(id="T1-P-H7", subject="fender bender, everyone's okay",
         body="Got in a small accident on the way home, everyone's okay but the car's not driveable, can you come pick me up right now?",
         to="partner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.78, true_bucket="high"),
    dict(id="T1-P-H8", subject="power's out and the sump pump stopped",
         body="Power just went out and the sump pump stopped, basement's going to flood if it's not back on soon, do you know anyone who can help right now?",
         to="brother@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.80, true_bucket="high"),
    dict(id="T1-P-H9", subject="having chest pains, going to the ER",
         body="I've been having chest pains for the last hour, heading to the ER now, can you meet me there?",
         to="partner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.99, true_bucket="high"),
    dict(id="T1-P-H10", subject="need you right now",
         body="i really need you to call me right now, something happened and i don't want to be alone",
         to="bestfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.85, true_bucket="high"),
    dict(id="T1-P-H11", subject="call now",
         body="call me now, it's about dad",
         to="sibling@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.94, true_bucket="high"),
    dict(id="T1-P-H12", subject="smoke in the hallway",
         body="i smell smoke in the hallway and the alarm just went off, getting everyone out now, call me when you can",
         to="roommate@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.95, true_bucket="high"),

    # ── Other - low (12) ─────────────────────────────────────────────────
    dict(id="T1-O-L1", subject="Your Larkspur Realty market report is ready",
         body="This month's local market report is ready to view online, covers recent sales trends in your area.",
         to="subscriber@gmail.com", from_addr="reports@larkspurrealty.com",
         true_category="Other", true_priority=0.16, true_bucket="low"),
    dict(id="T1-O-L2", subject="Maple Grove PTA newsletter - October",
         body="This month's PTA newsletter covers the book fair, staff appreciation week, and upcoming volunteer opportunities.",
         to="parents@maplegroveschools.org", from_addr="pta@maplegroveschools.org",
         true_category="Other", true_priority=0.15, true_bucket="low"),
    dict(id="T1-O-L3", subject="Your Nimbus Retail loyalty points summary",
         body="You've earned 340 points this quarter. Check your account anytime to see rewards you can redeem.",
         to="customer@gmail.com", from_addr="rewards@nimbusretail.com",
         true_category="Other", true_priority=0.13, true_bucket="low"),
    dict(id="T1-O-L4", subject="Alumni association fall gathering recap",
         body="Thanks to everyone who came out to the fall gathering, photos are posted on the alumni portal whenever you'd like to browse.",
         to="alumni@stateuniv.edu", from_addr="events@stateuniv-alumni.org",
         true_category="Other", true_priority=0.14, true_bucket="low"),
    dict(id="T1-O-L5", subject="Community garden plot availability",
         body="A few plots opened up for next season, no rush to decide, sign-ups stay open through the spring.",
         to="residents@fernwoodhoa.org", from_addr="garden@fernwoodhoa.org",
         true_category="Other", true_priority=0.17, true_bucket="low"),
    dict(id="T1-O-L6", subject="Your streaming service - new season available",
         body="A new season of a show you watched is now available. Check it out whenever you're in the mood.",
         to="viewer@gmail.com", from_addr="notify@streamflix.com",
         true_category="Other", true_priority=0.12, true_bucket="low"),
    dict(id="T1-O-L7", subject="Church bulletin for this Sunday",
         body="This week's bulletin is attached, covers the sermon topic and upcoming fellowship events. See you whenever you can make it.",
         to="congregation@rivercommunitychurch.org", from_addr="office@rivercommunitychurch.org",
         true_category="Other", true_priority=0.15, true_bucket="low"),
    dict(id="T1-O-L8", subject="Your utility usage report for last month",
         body="Your household used slightly less energy than last month, nice work. No action needed, just an FYI.",
         to="customer@gmail.com", from_addr="usage@cityutilities.gov",
         true_category="Other", true_priority=0.14, true_bucket="low"),
    dict(id="T1-O-L9", subject="Gym class schedule update for next month",
         body="A couple class times are shifting slightly next month, updated schedule is on the app whenever you want to check.",
         to="members@ironoakgym.com", from_addr="frontdesk@ironoakgym.com",
         true_category="Other", true_priority=0.16, true_bucket="low"),
    dict(id="T1-O-L10", subject="Your insurance policy summary is available",
         body="Your annual policy summary is ready to view online. Nothing has changed, this is just the yearly recap.",
         to="policyholder@gmail.com", from_addr="documents@shieldinsurance.com",
         true_category="Other", true_priority=0.13, true_bucket="low"),
    dict(id="T1-O-L11", subject="Book club pick for next month",
         body="Next month's pick is out, no pressure to finish it in time, we always end up chatting about other stuff anyway.",
         to="members@fernwoodhoa.org", from_addr="bookclub@fernwoodhoa.org",
         true_category="Other", true_priority=0.18, true_bucket="low"),
    dict(id="T1-O-L12", subject="thanks for coming to the tasting",
         body="thanks so much for coming out to the wine tasting last night, hope you had fun, hope to see you at the next one",
         to="member@vinecrestwinery.com", from_addr="events@vinecrestwinery.com",
         true_category="Other", true_priority=0.15, true_bucket="low"),

    # ── Other - medium (11) ──────────────────────────────────────────────
    dict(id="T1-O-M1", subject="Please confirm your annual checkup",
         body="Your annual checkup is coming up in the next couple weeks, please confirm you'll be attending or call to reschedule.",
         to="patient@gmail.com", from_addr="scheduling@alderleafhealth.com",
         true_category="Other", true_priority=0.37, true_bucket="medium"),
    dict(id="T1-O-M2", subject="HOA dues due soon",
         body="Quarterly HOA dues are due by the end of next week, please submit payment through the portal to avoid a late fee.",
         to="residents@fernwoodhoa.org", from_addr="treasurer@fernwoodhoa.org",
         true_category="Other", true_priority=0.42, true_bucket="medium"),
    dict(id="T1-O-M3", subject="Your car's registration expires this month",
         body="Reminder that your vehicle registration expires at the end of this month, please renew before then to avoid a fine.",
         to="driver@gmail.com", from_addr="notices@dmv.gov",
         true_category="Other", true_priority=0.44, true_bucket="medium"),
    dict(id="T1-O-M4", subject="Please RSVP for the alumni reunion",
         body="We need a headcount for catering soon, please RSVP by the end of the week if you're planning to attend the reunion.",
         to="alumni@stateuniv.edu", from_addr="events@stateuniv-alumni.org",
         true_category="Other", true_priority=0.38, true_bucket="medium"),
    dict(id="T1-O-M5", subject="Membership renewal needed soon",
         body="Your gym membership is up for renewal in two weeks, please update your payment info so you don't lose access.",
         to="member@ironoakgym.com", from_addr="billing@ironoakgym.com",
         true_category="Other", true_priority=0.40, true_bucket="medium"),
    dict(id="T1-O-M6", subject="Action needed: policy document signature",
         body="We need your signature on the updated policy document within the next week to keep your coverage active.",
         to="policyholder@gmail.com", from_addr="underwriting@shieldinsurance.com",
         true_category="Other", true_priority=0.45, true_bucket="medium"),
    dict(id="T1-O-M7", subject="Package requires signature - reschedule needed",
         body="We attempted delivery but a signature was required and no one was available. Please reschedule within the next few days.",
         to="customer@gmail.com", from_addr="delivery@swiftship.com",
         true_category="Other", true_priority=0.36, true_bucket="medium"),
    dict(id="T1-O-M8", subject="Please update your emergency contact info",
         body="It's been a while since your emergency contact info was updated on file, could you confirm it's still correct sometime this week?",
         to="patient@gmail.com", from_addr="records@alderleafhealth.com",
         true_category="Other", true_priority=0.35, true_bucket="medium"),
    dict(id="T1-O-M9", subject="Water shutoff notice for maintenance",
         body="Water will be shut off for scheduled maintenance next week for a few hours, please plan accordingly.",
         to="residents@fernwoodhoa.org", from_addr="maintenance@cityutilities.gov",
         true_category="Other", true_priority=0.41, true_bucket="medium"),
    dict(id="T1-O-M10", subject="Your flight itinerary has changed slightly",
         body="Your departure gate has changed for next week's flight, please review the updated itinerary before you travel.",
         to="traveler@gmail.com", from_addr="itinerary@skywingair.com",
         true_category="Other", true_priority=0.39, true_bucket="medium"),
    dict(id="T1-O-M11", subject="need you to confirm the pledge amount",
         body="could you confirm your pledge amount for the building fund sometime this week? want to finalize the total before the board meets",
         to="congregation@rivercommunitychurch.org", from_addr="office@rivercommunitychurch.org",
         true_category="Other", true_priority=0.37, true_bucket="medium"),

    # ── Other - high (9) ─────────────────────────────────────────────────
    dict(id="T1-O-H1", subject="Boil water advisory in effect immediately",
         body="A boil water advisory is now in effect for your area due to a main break. Do not drink tap water until further notice.",
         to="residents@fernwoodhoa.org", from_addr="alerts@cityutilities.gov",
         true_category="Other", true_priority=0.90, true_bucket="high"),
    dict(id="T1-O-H2", subject="Your policy will lapse tonight without payment",
         body="Your insurance payment failed and coverage lapses at midnight tonight unless it's resolved. Please call immediately.",
         to="policyholder@gmail.com", from_addr="billing@shieldinsurance.com",
         true_category="Other", true_priority=0.82, true_bucket="high"),
    dict(id="T1-O-H3", subject="Flight cancelled - rebooking required today",
         body="Your flight tomorrow has been cancelled. Please rebook today, seats on alternate flights are limited.",
         to="traveler@gmail.com", from_addr="alerts@skywingair.com",
         true_category="Other", true_priority=0.78, true_bucket="high"),
    dict(id="T1-O-H4", subject="Gas leak reported in your building",
         body="A gas leak has been reported in your building. Evacuate immediately and do not use any electrical switches.",
         to="residents@fernwoodhoa.org", from_addr="safety@cityutilities.gov",
         true_category="Other", true_priority=0.99, true_bucket="high"),
    dict(id="T1-O-H5", subject="Abnormal test result - please call us today",
         body="We received a test result that needs to be discussed right away. Please call the office as soon as possible today.",
         to="patient@gmail.com", from_addr="results@alderleafhealth.com",
         true_category="Other", true_priority=0.93, true_bucket="high"),
    dict(id="T1-O-H6", subject="Severe storm approaching your area",
         body="A severe storm with damaging winds is expected to hit your area within the hour. Secure loose items and take shelter.",
         to="residents@fernwoodhoa.org", from_addr="alerts@weatherservice.gov",
         true_category="Other", true_priority=0.88, true_bucket="high"),
    dict(id="T1-O-H7", subject="Fraud alert - unusual charge on your card",
         body="We detected a large, unusual charge on your account just now. If this wasn't you, please call us immediately to freeze the card.",
         to="cardholder@gmail.com", from_addr="fraud@shieldbank.com",
         true_category="Other", true_priority=0.85, true_bucket="high"),
    dict(id="T1-O-H8", subject="call us right away",
         body="please call the office right away, it's about your recent visit, we need to speak with you today",
         to="patient@gmail.com", from_addr="nurse@alderleafhealth.com",
         true_category="Other", true_priority=0.89, true_bucket="high"),
    dict(id="T1-O-H9", subject="evacuation notice",
         body="wildfire is approaching the area, evacuation ordered for your zone effective immediately, leave now",
         to="residents@fernwoodhoa.org", from_addr="alerts@weatherservice.gov",
         true_category="Other", true_priority=0.99, true_bucket="high"),
]

assert len(ROWS) == 100, f"expected 100, got {len(ROWS)}"
