"""
synthetic_priority_train_batch2.py — batch 2/5. See batch1 docstring for
methodology/fields. Distinct businesses/relationships/senders from batch 1
to keep lexical diversity high (a model shouldn't be able to learn
"Alderleaf Health = high priority" as a shortcut).
"""

ROWS = [
    # ── Work - low (11) ──────────────────────────────────────────────────
    dict(id="T2-W-L1", subject="Pixelforge Studios - sprint retro notes",
         body="Notes from yesterday's retro are in the wiki, nothing controversial came up, just archiving for the record.",
         to="dev-team@pixelforgestudios.com", from_addr="scrum@pixelforgestudios.com",
         true_category="Work", true_priority=0.17, true_bucket="low"),
    dict(id="T2-W-L2", subject="Willowbrook Vet - new exam room furniture arrived",
         body="The new furniture for exam room 3 arrived and is set up. No action needed, just letting everyone know.",
         to="staff@willowbrookvet.com", from_addr="office@willowbrookvet.com",
         true_category="Work", true_priority=0.15, true_bucket="low"),
    dict(id="T2-W-L3", subject="Ironclad Builders - safety training completed",
         body="This quarter's safety training session wrapped up yesterday, certificates are filed. Nothing further needed from the crew.",
         to="crew@ironcladbuilders.com", from_addr="safety@ironcladbuilders.com",
         true_category="Work", true_priority=0.16, true_bucket="low"),
    dict(id="T2-W-L4", subject="Bluewave Marketing - client testimonial posted",
         body="Posted the new client testimonial to the site, looks great. Thought the team would like to see it.",
         to="team@bluewavemarketing.com", from_addr="content@bluewavemarketing.com",
         true_category="Work", true_priority=0.14, true_bucket="low"),
    dict(id="T2-W-L5", subject="Sunnyside Daycare - art supplies restocked",
         body="Art supplies got restocked this week, thanks to whoever put in the order. All set for the month.",
         to="teachers@sunnysidedaycare.com", from_addr="director@sunnysidedaycare.com",
         true_category="Work", true_priority=0.13, true_bucket="low"),
    dict(id="T2-W-L6", subject="Timber Auto Repair - new diagnostic tool arrived",
         body="The new diagnostic scanner came in today, it's set up at bay 2 whenever anyone wants to try it out.",
         to="mechanics@timberautorepair.com", from_addr="shop-manager@timberautorepair.com",
         true_category="Work", true_priority=0.17, true_bucket="low"),
    dict(id="T2-W-L7", subject="Crestview Inn - great reviews this week",
         body="We got a few really nice reviews this week mentioning the front desk team by name, wanted to share the good news.",
         to="staff@crestviewinn.com", from_addr="gm@crestviewinn.com",
         true_category="Work", true_priority=0.15, true_bucket="low"),
    dict(id="T2-W-L8", subject="Riverside Theater Co - set pieces in storage",
         body="Moved last season's set pieces into the storage unit, all labeled. FYI for whenever we plan the next show.",
         to="crew@riversidetheaterco.org", from_addr="stage-manager@riversidetheaterco.org",
         true_category="Work", true_priority=0.16, true_bucket="low"),
    dict(id="T2-W-L9", subject="Golden Acres Farm - irrigation check went fine",
         body="Ran the irrigation check this morning, everything's working as expected. Nothing to report otherwise.",
         to="crew@goldenacresfarm.com", from_addr="foreman@goldenacresfarm.com",
         true_category="Work", true_priority=0.14, true_bucket="low"),
    dict(id="T2-W-L10", subject="Cipher Systems - new coffee machine in the break room",
         body="New coffee machine is up and running in the break room, previous one finally gave out. Enjoy.",
         to="staff@ciphersystems.com", from_addr="office-manager@ciphersystems.com",
         true_category="Work", true_priority=0.12, true_bucket="low"),
    dict(id="T2-W-L11", subject="good job this week",
         body="just wanted to say the team really pulled together this week, nice work all around, no reply needed",
         to="dev-team@pixelforgestudios.com", from_addr="scrum@pixelforgestudios.com",
         true_category="Work", true_priority=0.15, true_bucket="low"),

    # ── Work - medium (11) ───────────────────────────────────────────────
    dict(id="T2-W-M1", subject="Need your review on the new hire's code",
         body="Could you review the new hire's first PR sometime this week? Want to give feedback before their next sprint starts.",
         to="senior-dev@pixelforgestudios.com", from_addr="manager@pixelforgestudios.com",
         true_category="Work", true_priority=0.39, true_bucket="medium"),
    dict(id="T2-W-M2", subject="Please confirm the surgery schedule for next week",
         body="Could you confirm you're available for next week's scheduled surgeries? Need to finalize the calendar soon.",
         to="dr.patel@willowbrookvet.com", from_addr="scheduling@willowbrookvet.com",
         true_category="Work", true_priority=0.41, true_bucket="medium"),
    dict(id="T2-W-M3", subject="Permit paperwork needs your signature",
         body="The building permit paperwork needs your signature before we can submit it, could you swing by the office this week?",
         to="foreman@ironcladbuilders.com", from_addr="pm@ironcladbuilders.com",
         true_category="Work", true_priority=0.43, true_bucket="medium"),
    dict(id="T2-W-M4", subject="Client wants revised ad copy this week",
         body="The client asked for revised ad copy, could you get a draft together sometime before Thursday's check-in?",
         to="copywriter@bluewavemarketing.com", from_addr="account-mgr@bluewavemarketing.com",
         true_category="Work", true_priority=0.40, true_bucket="medium"),
    dict(id="T2-W-M5", subject="Need updated enrollment forms",
         body="A couple families still need to submit updated enrollment forms, could you follow up with them this week?",
         to="admin@sunnysidedaycare.com", from_addr="director@sunnysidedaycare.com",
         true_category="Work", true_priority=0.37, true_bucket="medium"),
    dict(id="T2-W-M6", subject="Parts order needs approval",
         body="The parts order for next week's jobs needs your approval, could you look it over sometime today or tomorrow?",
         to="shop-manager@timberautorepair.com", from_addr="parts-desk@timberautorepair.com",
         true_category="Work", true_priority=0.42, true_bucket="medium"),
    dict(id="T2-W-M7", subject="Need the banquet setup confirmed",
         body="Could you confirm the banquet hall setup for next weekend's event sometime this week? Vendor needs a final headcount soon.",
         to="events@crestviewinn.com", from_addr="gm@crestviewinn.com",
         true_category="Work", true_priority=0.44, true_bucket="medium"),
    dict(id="T2-W-M8", subject="Need your notes on the script revisions",
         body="Could you send your notes on the second act revisions sometime this week? Rehearsal schedule depends on it.",
         to="director@riversidetheaterco.org", from_addr="playwright@riversidetheaterco.org",
         true_category="Work", true_priority=0.38, true_bucket="medium"),
    dict(id="T2-W-M9", subject="Need the harvest schedule finalized",
         body="Could we finalize the harvest schedule for next week sometime in the next couple days? Need to line up the crew.",
         to="foreman@goldenacresfarm.com", from_addr="owner@goldenacresfarm.com",
         true_category="Work", true_priority=0.40, true_bucket="medium"),
    dict(id="T2-W-M10", subject="Need sign-off on the security patch rollout",
         body="Could you review and approve the patch rollout plan sometime this week? Want to schedule it before the month is out.",
         to="security-lead@ciphersystems.com", from_addr="engineer@ciphersystems.com",
         true_category="Work", true_priority=0.43, true_bucket="medium"),
    dict(id="T2-W-M11", subject="need feedback on the pitch deck",
         body="could you take a look at the pitch deck sometime this week? presenting it to the client soon and want another set of eyes",
         to="account-mgr@bluewavemarketing.com", from_addr="designer@bluewavemarketing.com",
         true_category="Work", true_priority=0.39, true_bucket="medium"),

    # ── Work - high (12) ─────────────────────────────────────────────────
    dict(id="T2-W-H1", subject="Production database is being hit by a DDoS attack",
         body="We're seeing a live DDoS attack against production right now, need the security team on the incident call immediately.",
         to="security-lead@ciphersystems.com", from_addr="oncall@ciphersystems.com",
         true_category="Work", true_priority=0.94, true_bucket="high"),
    dict(id="T2-W-H2", subject="Dog is coding, need the vet now",
         body="A dog just went into respiratory distress in the waiting room, need Dr. Patel back here immediately, this can't wait.",
         to="dr.patel@willowbrookvet.com", from_addr="tech@willowbrookvet.com",
         true_category="Work", true_priority=0.97, true_bucket="high"),
    dict(id="T2-W-H3", subject="Scaffolding just collapsed on site",
         body="Scaffolding collapsed on the east side of the site, need everyone off the floor and 911 called right now.",
         to="foreman@ironcladbuilders.com", from_addr="crew-lead@ironcladbuilders.com",
         true_category="Work", true_priority=0.99, true_bucket="high"),
    dict(id="T2-W-H4", subject="Campaign went live with the wrong pricing",
         body="The ad campaign just went live with the wrong pricing, it's already getting clicks, need this pulled down immediately.",
         to="account-mgr@bluewavemarketing.com", from_addr="analyst@bluewavemarketing.com",
         true_category="Work", true_priority=0.86, true_bucket="high"),
    dict(id="T2-W-H5", subject="Child is missing from the playground",
         body="We can't find one of the kids on the playground, need all hands searching right now and the parents called immediately.",
         to="director@sunnysidedaycare.com", from_addr="teacher@sunnysidedaycare.com",
         true_category="Work", true_priority=0.98, true_bucket="high"),
    dict(id="T2-W-H6", subject="Car caught fire on the lift",
         body="A customer's car just caught fire while up on the lift, everyone's clear but need the fire department called now.",
         to="shop-manager@timberautorepair.com", from_addr="mechanic@timberautorepair.com",
         true_category="Work", true_priority=0.97, true_bucket="high"),
    dict(id="T2-W-H7", subject="Guest collapsed in the lobby",
         body="A guest just collapsed in the lobby, we've called 911 but need the on-duty manager down here right now.",
         to="gm@crestviewinn.com", from_addr="frontdesk@crestviewinn.com",
         true_category="Work", true_priority=0.96, true_bucket="high"),
    dict(id="T2-W-H8", subject="Lead actor injured during rehearsal",
         body="The lead actor just took a bad fall during blocking, we've called for help, need you at the theater right now.",
         to="director@riversidetheaterco.org", from_addr="stage-manager@riversidetheaterco.org",
         true_category="Work", true_priority=0.90, true_bucket="high"),
    dict(id="T2-W-H9", subject="Frost warning tonight, need crew now",
         body="Unexpected frost warning just came in for tonight, need the crew out covering the fields within the hour or we lose the crop.",
         to="crew@goldenacresfarm.com", from_addr="owner@goldenacresfarm.com",
         true_category="Work", true_priority=0.89, true_bucket="high"),
    dict(id="T2-W-H10", subject="Client data may have been exposed",
         body="We think client data may have been exposed in the last deploy, need the security team investigating immediately, this is not a drill.",
         to="security-lead@ciphersystems.com", from_addr="cto@ciphersystems.com",
         true_category="Work", true_priority=0.99, true_bucket="high"),
    dict(id="T2-W-H11", subject="need you at the site now",
         body="get to the site right now, someone fell off the scaffolding, ambulance is on the way",
         to="foreman@ironcladbuilders.com", from_addr="crew-lead@ironcladbuilders.com",
         true_category="Work", true_priority=0.98, true_bucket="high"),
    dict(id="T2-W-H12", subject="call me right now",
         body="call me right now, the animal is crashing and we need you back here immediately",
         to="dr.patel@willowbrookvet.com", from_addr="tech@willowbrookvet.com",
         true_category="Work", true_priority=0.96, true_bucket="high"),

    # ── Personal - low (11) ──────────────────────────────────────────────
    dict(id="T2-P-L1", subject="aunt carol's garden is huge this year",
         body="Aunt Carol's tomatoes are out of control this year, she sent me way too many, thought you'd enjoy hearing about it.",
         to="nephew@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.14, true_bucket="low"),
    dict(id="T2-P-L2", subject="found our old dorm photos",
         body="Was going through boxes and found photos from our dorm days, wow we looked young. Sending a few over.",
         to="exroommate@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.15, true_bucket="low"),
    dict(id="T2-P-L3", subject="thanks for the advice last month",
         body="Just wanted to say the advice you gave me last month really helped, things worked out well. No need to reply.",
         to="mentor@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.16, true_bucket="low"),
    dict(id="T2-P-L4", subject="the kid next door is hilarious",
         body="The neighbor's kid asked me the funniest question today, had to share it with you, made my whole day.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.13, true_bucket="low"),
    dict(id="T2-P-L5", subject="finally hit my running goal",
         body="Finally hit the running goal we talked about at the gym, felt good to tell someone who'd actually get it.",
         to="gymbuddy@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.17, true_bucket="low"),
    dict(id="T2-P-L6", subject="loved this month's book pick",
         body="Really loved this month's book club pick, excited to talk about it whenever we all get together next.",
         to="bookclubfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.15, true_bucket="low"),
    dict(id="T2-P-L7", subject="in-laws are visiting next month",
         body="Just found out the in-laws are visiting next month, should be fun, will keep you posted on plans.",
         to="spouse-sibling@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.16, true_bucket="low"),
    dict(id="T2-P-L8", subject="godson's drawing made me tear up",
         body="Your son drew me a picture and it's now on my fridge, tell him it made my whole week.",
         to="godparent-friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.14, true_bucket="low"),
    dict(id="T2-P-L9", subject="remember this old inside joke",
         body="Saw something today that reminded me of that ridiculous inside joke from years ago, still makes me laugh.",
         to="childhoodfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.13, true_bucket="low"),
    dict(id="T2-P-L10", subject="new coworker is actually really fun",
         body="The new coworker I mentioned turned out to be really fun, we grabbed lunch today, thought you'd want the update.",
         to="workfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.15, true_bucket="low"),
    dict(id="T2-P-L11", subject="lol look what the dog did now",
         body="lol the dog dug up half the yard again, sending pics, not even mad anymore honestly",
         to="friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.12, true_bucket="low"),

    # ── Personal - medium (11) ───────────────────────────────────────────
    dict(id="T2-P-M1", subject="can you help me move the couch this weekend?",
         body="Moving a new couch in this weekend and could use an extra pair of hands, are you free Saturday? Let me know soon.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.38, true_bucket="medium"),
    dict(id="T2-P-M2", subject="need an answer on babysitting next friday",
         body="Could you babysit next Friday night? Need to know by Wednesday so I can book a sitter elsewhere if not.",
         to="neighbor@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.42, true_bucket="medium"),
    dict(id="T2-P-M3", subject="can we talk about splitting mom's care?",
         body="We should talk soon about how to split up helping with mom's care, are you free to call sometime this week?",
         to="sibling@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.44, true_bucket="medium"),
    dict(id="T2-P-M4", subject="need the number for your contractor",
         body="Could you send me your contractor's number sometime this week? Trying to get quotes before the month's out.",
         to="workfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.33, true_bucket="medium"),
    dict(id="T2-P-M5", subject="planning the surprise party details",
         body="We need to lock in the venue for the surprise party soon, can you confirm your part of the plan by this weekend?",
         to="friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.40, true_bucket="medium"),
    dict(id="T2-P-M6", subject="need to return your ladder",
         body="I still have your ladder, want it back sometime this week? Happy to drop it off whenever works.",
         to="neighbor@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.30, true_bucket="medium"),
    dict(id="T2-P-M7", subject="can you write me a reference this week?",
         body="Would you be able to write a quick reference letter sometime this week? I need to submit it fairly soon.",
         to="mentor@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.41, true_bucket="medium"),
    dict(id="T2-P-M8", subject="need to plan mom and dad's anniversary",
         body="Their anniversary is coming up in a few weeks, want to start planning something together soon so we're not scrambling?",
         to="sibling@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.39, true_bucket="medium"),
    dict(id="T2-P-M9", subject="can you cover my shift at the co-op",
         body="Any chance you could cover my volunteer shift at the co-op this week? Need to know soon so I can find someone else if not.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.37, true_bucket="medium"),
    dict(id="T2-P-M10", subject="need help deciding on the apartment",
         body="Torn between two apartments and need to decide by the weekend, could we talk it through sometime soon?",
         to="bestfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.36, true_bucket="medium"),
    dict(id="T2-P-M11", subject="need your part of the gift money soon",
         body="hey, ordering the group gift this week, can you send your share sometime before friday?",
         to="workfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.34, true_bucket="medium"),

    # ── Personal - high (12) ─────────────────────────────────────────────
    dict(id="T2-P-H1", subject="dad collapsed at home",
         body="Dad just collapsed at home, ambulance is on the way, please call me the second you see this.",
         to="sibling@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.99, true_bucket="high"),
    dict(id="T2-P-H2", subject="my son isn't breathing right, calling 911",
         body="My son is having trouble breathing, I'm calling 911 now, please come to the house as soon as you can.",
         to="spouse-sibling@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.99, true_bucket="high"),
    dict(id="T2-P-H3", subject="kitchen fire, everyone's out",
         body="There's a fire in the kitchen, we're all out of the house safely but need the fire department and you here right away.",
         to="neighbor@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.97, true_bucket="high"),
    dict(id="T2-P-H4", subject="mentor had a stroke",
         body="Just heard my mentor had a stroke and is in the hospital, please call me when you get a chance, I need to talk to someone.",
         to="mentor@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.85, true_bucket="high"),
    dict(id="T2-P-H5", subject="car went off the road, I'm okay but need help",
         body="I slid off the road in the storm, I'm okay but the car's stuck and I'm freezing, can you come get me right now?",
         to="friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.88, true_bucket="high"),
    dict(id="T2-P-H6", subject="basement is filling with water fast",
         body="Basement is filling with water fast from the storm, I can't keep up bailing it out, can you come help right now?",
         to="neighbor@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.81, true_bucket="high"),
    dict(id="T2-P-H7", subject="think I'm having an allergic reaction",
         body="My face is swelling up and I don't know why, I think I'm having a reaction, can you come now or tell me what to do.",
         to="bestfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.94, true_bucket="high"),
    dict(id="T2-P-H8", subject="landlord is trying to change the locks today",
         body="Landlord just showed up saying he's changing the locks today, this feels illegal, can you call me right now, I need advice.",
         to="workfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.79, true_bucket="high"),
    dict(id="T2-P-H9", subject="the baby is coming, heading to the hospital",
         body="Water just broke, we're heading to the hospital right now, get here as soon as you can.",
         to="spouse-sibling@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.98, true_bucket="high"),
    dict(id="T2-P-H10", subject="please pick up",
         body="please pick up the phone, it's an emergency, call me back the second you see this",
         to="sibling@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.90, true_bucket="high"),
    dict(id="T2-P-H11", subject="need you now",
         body="i really need you right now, please just call, i'll explain when you call",
         to="bestfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.83, true_bucket="high"),
    dict(id="T2-P-H12", subject="911 dad",
         body="dad's not responding, ambulance coming, please come now",
         to="sibling@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.99, true_bucket="high"),

    # ── Other - low (12) ─────────────────────────────────────────────────
    dict(id="T2-O-L1", subject="Your pharmacy loyalty points update",
         body="You've earned points on recent purchases, no action needed, just an update on your account.",
         to="customer@gmail.com", from_addr="rewards@wellspringpharmacy.com",
         true_category="Other", true_priority=0.13, true_bucket="low"),
    dict(id="T2-O-L2", subject="Library new arrivals this month",
         body="New titles just arrived in the mystery and history sections, browse online whenever you're curious.",
         to="patrons@cityLibrary.org", from_addr="newsletter@citylibrary.org",
         true_category="Other", true_priority=0.14, true_bucket="low"),
    dict(id="T2-O-L3", subject="Museum member spotlight - new exhibit preview",
         body="A sneak preview of next season's exhibit is up on the members' portal, take a look whenever you have time.",
         to="members@artcitymuseum.org", from_addr="membership@artcitymuseum.org",
         true_category="Other", true_priority=0.16, true_bucket="low"),
    dict(id="T2-O-L4", subject="Your service department visit summary",
         body="Here's a summary of your recent visit and what was done. No action needed, just for your records.",
         to="customer@gmail.com", from_addr="service@crestlinemotors.com",
         true_category="Other", true_priority=0.12, true_bucket="low"),
    dict(id="T2-O-L5", subject="Your internet plan - no changes needed",
         body="Just confirming your plan renewed at the same rate as before, nothing you need to do.",
         to="customer@gmail.com", from_addr="billing@clearlinkisp.com",
         true_category="Other", true_priority=0.15, true_bucket="low"),
    dict(id="T2-O-L6", subject="Your mobile plan usage summary",
         body="You used less data than usual this month, nice. No action needed, just an FYI.",
         to="customer@gmail.com", from_addr="usage@orbitmobile.com",
         true_category="Other", true_priority=0.13, true_bucket="low"),
    dict(id="T2-O-L7", subject="Your pet insurance annual summary",
         body="Here's a look back at your pet's coverage this year. Nothing needed from you, just a recap.",
         to="policyholder@gmail.com", from_addr="reports@pawshieldinsurance.com",
         true_category="Other", true_priority=0.14, true_bucket="low"),
    dict(id="T2-O-L8", subject="Your food delivery order has arrived",
         body="Your order was delivered, enjoy the meal. No action needed unless something's wrong.",
         to="customer@gmail.com", from_addr="orders@quickbiteapp.com",
         true_category="Other", true_priority=0.11, true_bucket="low"),
    dict(id="T2-O-L9", subject="Marketplace listing update",
         body="Your listing got a few more views this week, no action needed, just a stat update.",
         to="seller@gmail.com", from_addr="notify@tradepostmarket.com",
         true_category="Other", true_priority=0.13, true_bucket="low"),
    dict(id="T2-O-L10", subject="Financial aid office - FAFSA reminder for next year",
         body="Just a heads up that next year's FAFSA opens in a few months, nothing to do yet, just a heads up.",
         to="student@stateuniv.edu", from_addr="finaid@stateuniv.edu",
         true_category="Other", true_priority=0.16, true_bucket="low"),
    dict(id="T2-O-L11", subject="City parks department - trail maintenance complete",
         body="The trail maintenance on the north loop finished ahead of schedule, trail's open again for whenever you want to use it.",
         to="residents@fernwoodhoa.org", from_addr="parks@citygov.org",
         true_category="Other", true_priority=0.15, true_bucket="low"),
    dict(id="T2-O-L12", subject="credit union rate update - fyi",
         body="just an fyi that savings rates ticked up slightly this month, nothing you need to do, account updates automatically",
         to="member@meadowlarkcu.org", from_addr="notices@meadowlarkcu.org",
         true_category="Other", true_priority=0.12, true_bucket="low"),

    # ── Other - medium (11) ──────────────────────────────────────────────
    dict(id="T2-O-M1", subject="Please confirm your dental cleaning appointment",
         body="Your cleaning is scheduled for next week, please confirm or call to reschedule sometime soon.",
         to="patient@gmail.com", from_addr="scheduling@brightsmiledental.com",
         true_category="Other", true_priority=0.36, true_bucket="medium"),
    dict(id="T2-O-M2", subject="Please renew your library card soon",
         body="Your library card expires in a couple weeks, please renew online or in person to keep borrowing privileges.",
         to="patron@citylibrary.org", from_addr="circulation@citylibrary.org",
         true_category="Other", true_priority=0.34, true_bucket="medium"),
    dict(id="T2-O-M3", subject="Museum membership expiring soon",
         body="Your membership expires at the end of the month, renew soon to keep access to member events.",
         to="member@artcitymuseum.org", from_addr="membership@artcitymuseum.org",
         true_category="Other", true_priority=0.35, true_bucket="medium"),
    dict(id="T2-O-M4", subject="Vehicle recall notice - action needed",
         body="Your vehicle is affected by a recall, please schedule service within the next month to have it addressed.",
         to="owner@gmail.com", from_addr="recalls@crestlinemotors.com",
         true_category="Other", true_priority=0.44, true_bucket="medium"),
    dict(id="T2-O-M5", subject="Please update your account before the outage",
         body="We're migrating systems next week, please update your saved payment info before then to avoid service interruption.",
         to="customer@gmail.com", from_addr="notices@clearlinkisp.com",
         true_category="Other", true_priority=0.40, true_bucket="medium"),
    dict(id="T2-O-M6", subject="Your plan is changing, review needed",
         body="Your current mobile plan is being phased out, please review the new options and select one before next billing cycle.",
         to="customer@gmail.com", from_addr="plans@orbitmobile.com",
         true_category="Other", true_priority=0.42, true_bucket="medium"),
    dict(id="T2-O-M7", subject="Pet insurance claim needs more info",
         body="We need a bit more information to process your recent claim, please respond within the next couple weeks.",
         to="policyholder@gmail.com", from_addr="claims@pawshieldinsurance.com",
         true_category="Other", true_priority=0.38, true_bucket="medium"),
    dict(id="T2-O-M8", subject="Your delivery driver couldn't find the address",
         body="Your order couldn't be delivered, driver had trouble finding the address, please confirm details so we can retry.",
         to="customer@gmail.com", from_addr="support@quickbiteapp.com",
         true_category="Other", true_priority=0.37, true_bucket="medium"),
    dict(id="T2-O-M9", subject="Buyer has a question about your listing",
         body="Someone's interested in your listing and asked a question, please respond within a few days so they don't move on.",
         to="seller@gmail.com", from_addr="notify@tradepostmarket.com",
         true_category="Other", true_priority=0.33, true_bucket="medium"),
    dict(id="T2-O-M10", subject="Financial aid documents needed soon",
         body="We're still missing a document for your financial aid file, please submit it within the next two weeks to avoid delays.",
         to="student@stateuniv.edu", from_addr="finaid@stateuniv.edu",
         true_category="Other", true_priority=0.43, true_bucket="medium"),
    dict(id="T2-O-M11", subject="park permit needs a follow up",
         body="we need one more form for your park event permit, can you send it sometime this week so we can finalize approval",
         to="organizer@gmail.com", from_addr="parks@citygov.org",
         true_category="Other", true_priority=0.36, true_bucket="medium"),

    # ── Other - high (9) ─────────────────────────────────────────────────
    dict(id="T2-O-H1", subject="Your card was declined for a large suspicious charge",
         body="A large charge attempt was blocked on your card just now. If this wasn't you, call us immediately to secure your account.",
         to="member@meadowlarkcu.org", from_addr="fraud@meadowlarkcu.org",
         true_category="Other", true_priority=0.86, true_bucket="high"),
    dict(id="T2-O-H2", subject="Boil water notice - effective now",
         body="Do not drink tap water until further notice, a contamination issue was detected in your area's supply.",
         to="residents@fernwoodhoa.org", from_addr="alerts@citygov.org",
         true_category="Other", true_priority=0.91, true_bucket="high"),
    dict(id="T2-O-H3", subject="Your financial aid is at risk of being cancelled",
         body="Your financial aid will be cancelled if a required form isn't submitted by end of day today.",
         to="student@stateuniv.edu", from_addr="finaid@stateuniv.edu",
         true_category="Other", true_priority=0.80, true_bucket="high"),
    dict(id="T2-O-H4", subject="Urgent recall - stop driving the vehicle",
         body="This recall affects your brakes and is a safety risk, please stop driving the vehicle and schedule service immediately.",
         to="owner@gmail.com", from_addr="recalls@crestlinemotors.com",
         true_category="Other", true_priority=0.93, true_bucket="high"),
    dict(id="T2-O-H5", subject="Internet and phone service down in your area - emergency line info",
         body="All service is down in your area including emergency-line-capable phone service, restoration crews are working on it now, if you have a medical emergency use a neighbor's phone or go to a hospital directly.",
         to="customer@gmail.com", from_addr="alerts@clearlinkisp.com",
         true_category="Other", true_priority=0.84, true_bucket="high"),
    dict(id="T2-O-H6", subject="Abnormal test result on your pet - call now",
         body="Your pet's recent bloodwork came back with a result that needs urgent attention, please call the clinic right away.",
         to="policyholder@gmail.com", from_addr="clinic@pawshieldinsurance.com",
         true_category="Other", true_priority=0.87, true_bucket="high"),
    dict(id="T2-O-H7", subject="Tornado warning issued for your location",
         body="A tornado warning was just issued for your exact location, take shelter immediately away from windows.",
         to="residents@fernwoodhoa.org", from_addr="alerts@citygov.org",
         true_category="Other", true_priority=0.99, true_bucket="high"),
    dict(id="T2-O-H8", subject="call now about your account",
         body="please call us immediately, there is unusual activity on your account that needs to be verified right now",
         to="member@meadowlarkcu.org", from_addr="security@meadowlarkcu.org",
         true_category="Other", true_priority=0.85, true_bucket="high"),
    dict(id="T2-O-H9", subject="evacuate now",
         body="flooding is rising fast in your area, evacuate immediately, do not wait",
         to="residents@fernwoodhoa.org", from_addr="alerts@citygov.org",
         true_category="Other", true_priority=0.99, true_bucket="high"),
]

assert len(ROWS) == 100, f"expected 100, got {len(ROWS)}"
