"""
synthetic_priority_train_batch3.py — batch 3/5. See batch1 docstring.
New businesses/relationships/senders again, no repeats from batch1/2.
"""

ROWS = [
    # ── Work - low (11) ──────────────────────────────────────────────────
    dict(id="T3-W-L1", subject="Thornfield Lab - equipment calibration logged",
         body="Logged this month's equipment calibration in the shared sheet, all instruments passed. Nothing further needed.",
         to="researchers@thornfieldlab.edu", from_addr="lab-manager@thornfieldlab.edu",
         true_category="Work", true_priority=0.16, true_bucket="low"),
    dict(id="T3-W-L2", subject="Ledger & Vance - filing cabinet reorganized",
         body="Reorganized the archive filing cabinet this week, everything's labeled by year now. FYI for anyone searching old files.",
         to="staff@ledgervance.com", from_addr="office-manager@ledgervance.com",
         true_category="Work", true_priority=0.14, true_bucket="low"),
    dict(id="T3-W-L3", subject="Redwood Roasting - new bean sample arrived",
         body="A sample bag of the new Ethiopian lot arrived, sitting on the cupping table whenever anyone wants to try it.",
         to="roasters@redwoodroasting.com", from_addr="head-roaster@redwoodroasting.com",
         true_category="Work", true_priority=0.15, true_bucket="low"),
    dict(id="T3-W-L4", subject="Swift Movers - truck maintenance done",
         body="Truck 4 finished its routine maintenance, back in the lot and ready for next week's jobs.",
         to="drivers@swiftmovers.com", from_addr="dispatch@swiftmovers.com",
         true_category="Work", true_priority=0.13, true_bucket="low"),
    dict(id="T3-W-L5", subject="Pinecrest Orthodontics - waiting room magazines updated",
         body="Swapped out the waiting room magazines for newer issues, small thing but thought I'd mention it.",
         to="staff@pinecrestortho.com", from_addr="office-manager@pinecrestortho.com",
         true_category="Work", true_priority=0.12, true_bucket="low"),
    dict(id="T3-W-L6", subject="Grand Regal Cinema - popcorn machine serviced",
         body="Popcorn machine got its yearly service, running better than ever. No action needed from anyone.",
         to="staff@grandregalcinema.com", from_addr="manager@grandregalcinema.com",
         true_category="Work", true_priority=0.14, true_bucket="low"),
    dict(id="T3-W-L7", subject="Everside Landscaping - mower blades sharpened",
         body="Got all the mower blades sharpened ahead of the season, equipment's ready to go whenever we start.",
         to="crew@eversidelandscaping.com", from_addr="foreman@eversidelandscaping.com",
         true_category="Work", true_priority=0.16, true_bucket="low"),
    dict(id="T3-W-L8", subject="KKZY Radio - new intro jingle recorded",
         body="Finished recording the new morning show jingle, it's in the shared folder whenever you want a listen.",
         to="onair@kkzyradio.com", from_addr="producer@kkzyradio.com",
         true_category="Work", true_priority=0.15, true_bucket="low"),
    dict(id="T3-W-L9", subject="Flourish Bakery - new oven thermometer installed",
         body="Installed the new oven thermometer, readings look accurate now. Just an FYI, nothing needed.",
         to="bakers@flourishbakery.com", from_addr="head-baker@flourishbakery.com",
         true_category="Work", true_priority=0.13, true_bucket="low"),
    dict(id="T3-W-L10", subject="Northgate IT - ticket backlog cleared",
         body="Cleared out the old ticket backlog this week, queue's looking clean. Nice work team.",
         to="techs@northgateit.com", from_addr="lead@northgateit.com",
         true_category="Work", true_priority=0.14, true_bucket="low"),
    dict(id="T3-W-L11", subject="nice job on the tasting event",
         body="just wanted to say the cupping event went really well saturday, good energy from the whole team, no reply needed",
         to="roasters@redwoodroasting.com", from_addr="head-roaster@redwoodroasting.com",
         true_category="Work", true_priority=0.15, true_bucket="low"),

    # ── Work - medium (11) ───────────────────────────────────────────────
    dict(id="T3-W-M1", subject="Need your review on the grant proposal draft",
         body="Could you review the grant proposal draft sometime this week? Want your comments before we submit next month.",
         to="pi@thornfieldlab.edu", from_addr="postdoc@thornfieldlab.edu",
         true_category="Work", true_priority=0.39, true_bucket="medium"),
    dict(id="T3-W-M2", subject="Client's tax documents still needed",
         body="We're still missing a couple documents from the Hendricks file, could you follow up with them sometime this week?",
         to="associate@ledgervance.com", from_addr="partner@ledgervance.com",
         true_category="Work", true_priority=0.42, true_bucket="medium"),
    dict(id="T3-W-M3", subject="Need the new blend name decided",
         body="We need to settle on a name for the new blend sometime this week, marketing wants to start on packaging soon.",
         to="head-roaster@redwoodroasting.com", from_addr="marketing@redwoodroasting.com",
         true_category="Work", true_priority=0.37, true_bucket="medium"),
    dict(id="T3-W-M4", subject="Need the route schedule confirmed",
         body="Could you confirm next week's delivery routes sometime today or tomorrow? Need to lock in driver assignments.",
         to="dispatch@swiftmovers.com", from_addr="ops-manager@swiftmovers.com",
         true_category="Work", true_priority=0.41, true_bucket="medium"),
    dict(id="T3-W-M5", subject="Need patient records transferred this week",
         body="A patient is switching providers and needs their records sent over, could you take care of it sometime this week?",
         to="office-manager@pinecrestortho.com", from_addr="dr.reyes@pinecrestortho.com",
         true_category="Work", true_priority=0.38, true_bucket="medium"),
    dict(id="T3-W-M6", subject="Need the concession order finalized",
         body="Could you finalize the concession supply order sometime this week? Want it in before the weekend rush.",
         to="manager@grandregalcinema.com", from_addr="assistant-manager@grandregalcinema.com",
         true_category="Work", true_priority=0.40, true_bucket="medium"),
    dict(id="T3-W-M7", subject="Need the new client quote approved",
         body="Could you approve the quote for the new client sometime this week? They're waiting to schedule the work.",
         to="foreman@eversidelandscaping.com", from_addr="sales@eversidelandscaping.com",
         true_category="Work", true_priority=0.43, true_bucket="medium"),
    dict(id="T3-W-M8", subject="Need the interview segment approved",
         body="Could you listen to the interview segment sometime this week and approve it for air? Want to get it queued up soon.",
         to="producer@kkzyradio.com", from_addr="host@kkzyradio.com",
         true_category="Work", true_priority=0.36, true_bucket="medium"),
    dict(id="T3-W-M9", subject="Need the wholesale order confirmed",
         body="Could you confirm this week's wholesale order numbers sometime today? Need to plan the baking schedule around it.",
         to="head-baker@flourishbakery.com", from_addr="office@flourishbakery.com",
         true_category="Work", true_priority=0.39, true_bucket="medium"),
    dict(id="T3-W-M10", subject="Need the server migration plan reviewed",
         body="Could you review the server migration plan sometime this week? Want to schedule it before end of month.",
         to="lead@northgateit.com", from_addr="tech@northgateit.com",
         true_category="Work", true_priority=0.42, true_bucket="medium"),
    dict(id="T3-W-M11", subject="need feedback on the lab safety draft",
         body="could you look over the updated lab safety procedures sometime this week? want to circulate it before next semester",
         to="pi@thornfieldlab.edu", from_addr="postdoc@thornfieldlab.edu",
         true_category="Work", true_priority=0.38, true_bucket="medium"),

    # ── Work - high (12) ─────────────────────────────────────────────────
    dict(id="T3-W-H1", subject="Sample freezer failed overnight, samples at risk",
         body="The -80 freezer failed overnight and years of samples are thawing, need everyone available to help transfer them right now.",
         to="researchers@thornfieldlab.edu", from_addr="lab-manager@thornfieldlab.edu",
         true_category="Work", true_priority=0.95, true_bucket="high"),
    dict(id="T3-W-H2", subject="IRS audit letter just arrived for a client",
         body="A client just got an audit letter with a response deadline this week, need someone on this immediately.",
         to="partner@ledgervance.com", from_addr="associate@ledgervance.com",
         true_category="Work", true_priority=0.84, true_bucket="high"),
    dict(id="T3-W-H3", subject="Roaster caught fire",
         body="The main roaster just caught fire, everyone's evacuated safely but need the fire department and owner right now.",
         to="head-roaster@redwoodroasting.com", from_addr="staff@redwoodroasting.com",
         true_category="Work", true_priority=0.98, true_bucket="high"),
    dict(id="T3-W-H4", subject="Truck accident on the highway, driver hurt",
         body="One of our trucks was in an accident on the highway, driver is hurt but conscious, need dispatch coordinating with EMS right now.",
         to="dispatch@swiftmovers.com", from_addr="driver@swiftmovers.com",
         true_category="Work", true_priority=0.97, true_bucket="high"),
    dict(id="T3-W-H5", subject="Patient having a reaction in the chair",
         body="A patient is having a reaction to the anesthesia right now, need Dr. Reyes back here immediately.",
         to="dr.reyes@pinecrestortho.com", from_addr="assistant@pinecrestortho.com",
         true_category="Work", true_priority=0.99, true_bucket="high"),
    dict(id="T3-W-H6", subject="Projector caught fire during the show",
         body="The projector just started smoking mid-film and we had to evacuate the theater, need the fire department and owner now.",
         to="manager@grandregalcinema.com", from_addr="staff@grandregalcinema.com",
         true_category="Work", true_priority=0.93, true_bucket="high"),
    dict(id="T3-W-H7", subject="Crew member collapsed from heat",
         body="One of the crew just collapsed from heat exhaustion on site, called 911, need you here right now.",
         to="foreman@eversidelandscaping.com", from_addr="crew@eversidelandscaping.com",
         true_category="Work", true_priority=0.96, true_bucket="high"),
    dict(id="T3-W-H8", subject="Transmitter went down mid-broadcast",
         body="We just lost the transmitter live on air, need engineering on this immediately or we're off the air county-wide.",
         to="lead@northgateit.com", from_addr="producer@kkzyradio.com",
         true_category="Work", true_priority=0.87, true_bucket="high"),
    dict(id="T3-W-H9", subject="Gas smell in the kitchen",
         body="We smell gas strongly in the kitchen, evacuating now, need someone to call the gas company and the owner immediately.",
         to="head-baker@flourishbakery.com", from_addr="staff@flourishbakery.com",
         true_category="Work", true_priority=0.98, true_bucket="high"),
    dict(id="T3-W-H10", subject="Ransomware alert triggered on the file server",
         body="Ransomware just triggered on the main file server, need it isolated from the network immediately before it spreads further.",
         to="lead@northgateit.com", from_addr="tech@northgateit.com",
         true_category="Work", true_priority=0.97, true_bucket="high"),
    dict(id="T3-W-H11", subject="get here now",
         body="get to the site now, someone got hurt with the equipment, ambulance called",
         to="foreman@eversidelandscaping.com", from_addr="crew@eversidelandscaping.com",
         true_category="Work", true_priority=0.96, true_bucket="high"),
    dict(id="T3-W-H12", subject="call me now",
         body="call me right now, the samples are ruined unless we move fast, need you here",
         to="researchers@thornfieldlab.edu", from_addr="lab-manager@thornfieldlab.edu",
         true_category="Work", true_priority=0.92, true_bucket="high"),

    # ── Personal - low (11) ──────────────────────────────────────────────
    dict(id="T3-P-L1", subject="stepmom sent the funniest text",
         body="Stepmom sent the most random text today, had to share it with you, she's too much sometimes.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.13, true_bucket="low"),
    dict(id="T3-P-L2", subject="ex and I actually get along now",
         body="Ran into my ex at the store today, weirdly it wasn't awkward at all, kind of nice actually. Thought I'd share.",
         to="bestfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.15, true_bucket="low"),
    dict(id="T3-P-L3", subject="choir practice was a mess today, in a good way",
         body="Choir practice was chaotic today, half the sopranos were sick, but somehow it was still a good time. Miss you being there.",
         to="choirfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.16, true_bucket="low"),
    dict(id="T3-P-L4", subject="league game recap",
         body="We actually won our rec league game last night, first time all season, had to tell someone who'd care.",
         to="teammate@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.14, true_bucket="low"),
    dict(id="T3-P-L5", subject="stepdad's fishing trip stories",
         body="Stepdad went on another one of his fishing trips and came back with the wildest stories as usual, thought you'd enjoy this one.",
         to="cousin@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.15, true_bucket="low"),
    dict(id="T3-P-L6", subject="my kid said something hilarious",
         body="My kid said the funniest thing at dinner tonight, had to write it down before I forgot, thought you'd get a laugh too.",
         to="mentor-spouse@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.13, true_bucket="low"),
    dict(id="T3-P-L7", subject="found our old camp photos",
         body="Found a box of photos from summer camp, can't believe how long ago that was, sending a few your way.",
         to="childhoodfriend2@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.16, true_bucket="low"),
    dict(id="T3-P-L8", subject="caregiving update, nothing new",
         body="Mom's doing about the same this week, nothing new to report, just wanted to keep you in the loop like always.",
         to="caregiver-friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.18, true_bucket="low"),
    dict(id="T3-P-L9", subject="adult son's new apartment looks great",
         body="Went to see your new place today, it looks amazing, so proud of you, no need to respond just wanted you to know.",
         to="adultchild@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.14, true_bucket="low"),
    dict(id="T3-P-L10", subject="lol you have to see the game footage",
         body="lol someone got video of me tripping during the game last night, sending it before you see it somewhere else first",
         to="teammate@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.12, true_bucket="low"),
    dict(id="T3-P-L11", subject="thinking about you today",
         body="hey just thinking about you, hope everything's going okay, no need to write back right away",
         to="caregiver-friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.15, true_bucket="low"),

    # ── Personal - medium (11) ───────────────────────────────────────────
    dict(id="T3-P-M1", subject="can you take mom to her appointment thursday?",
         body="I have a conflict Thursday, any chance you could take mom to her appointment? Need to know soon so I can arrange something else if not.",
         to="caregiver-friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.43, true_bucket="medium"),
    dict(id="T3-P-M2", subject="need to figure out custody schedule for the holidays",
         body="We should figure out the holiday schedule soon, are you free to talk sometime this week before things get busy?",
         to="ex-partner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.42, true_bucket="medium"),
    dict(id="T3-P-M3", subject="can you sub for me at choir this week?",
         body="I might not make it to choir this week, any chance you could let the director know or find someone to cover my part?",
         to="choirfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.32, true_bucket="medium"),
    dict(id="T3-P-M4", subject="need to know if you're playing this season",
         body="Signups for the league close soon, are you playing this season? Need a headcount before I register the team.",
         to="teammate@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.36, true_bucket="medium"),
    dict(id="T3-P-M5", subject="can you help me with the college essay?",
         body="My essay is due to my counselor soon, could you read it over sometime this week and give feedback?",
         to="mentor@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.40, true_bucket="medium"),
    dict(id="T3-P-M6", subject="need a ride to the airport next week",
         body="Could you give me a ride to the airport next week? Let me know soon so I can book a car service if not.",
         to="cousin@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.38, true_bucket="medium"),
    dict(id="T3-P-M7", subject="need your half of the camp fees",
         body="Camp fees are due soon, can you send your half sometime this week so I can pay the full amount?",
         to="ex-partner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.41, true_bucket="medium"),
    dict(id="T3-P-M8", subject="need help watching the kids this weekend",
         body="Could you watch the kids for a couple hours this weekend? Let me know soon so I can plan around it either way.",
         to="mentor-spouse@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.39, true_bucket="medium"),
    dict(id="T3-P-M9", subject="need an answer on the camping trip",
         body="Need to know by this weekend if you're coming on the camping trip so I can finalize the site reservation.",
         to="childhoodfriend2@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.37, true_bucket="medium"),
    dict(id="T3-P-M10", subject="can we talk about the caregiving schedule",
         body="I think we need to revisit who's covering what for mom's care, can we talk sometime this week? Nothing urgent, just overdue.",
         to="caregiver-friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.44, true_bucket="medium"),
    dict(id="T3-P-M11", subject="need you to sign the school form soon",
         body="hey, the school needs your signature on the field trip form by this week, can you send it back when you get a chance?",
         to="ex-partner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.40, true_bucket="medium"),

    # ── Personal - high (12) ─────────────────────────────────────────────
    dict(id="T3-P-H1", subject="mom is unresponsive, calling 911",
         body="Mom's unresponsive and I'm calling 911 right now, please get here as fast as you can.",
         to="caregiver-friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.99, true_bucket="high"),
    dict(id="T3-P-H2", subject="our kid is missing from the park",
         body="I can't find our son at the park, I've looked everywhere, please come now and call the police.",
         to="ex-partner@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.99, true_bucket="high"),
    dict(id="T3-P-H3", subject="choir friend's husband collapsed",
         body="Your husband just collapsed at rehearsal, we've called 911, please get to the church right away.",
         to="choirfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.98, true_bucket="high"),
    dict(id="T3-P-H4", subject="teammate got hurt bad during the game",
         body="You got hurt pretty bad on that last play, ambulance is coming, wanted you to see this the second you're okay to check your phone.",
         to="teammate@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.90, true_bucket="high"),
    dict(id="T3-P-H5", subject="mentor's wife needs help right now",
         body="Something happened at the house and I need help right now, can you call me the second you see this.",
         to="mentor-spouse@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.87, true_bucket="high"),
    dict(id="T3-P-H6", subject="cousin's car flipped, everyone's okay but shaken",
         body="Just got in an accident, car flipped, everyone's okay but shaken up badly, can you come get us right now.",
         to="cousin@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.92, true_bucket="high"),
    dict(id="T3-P-H7", subject="adult child locked out in the cold",
         body="I'm locked out and it's freezing, can't reach the landlord, can you come let me in or help me figure this out right now?",
         to="adultchild@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.78, true_bucket="high"),
    dict(id="T3-P-H8", subject="stepdad had a heart attack",
         body="Stepdad just had a heart attack, we're at the hospital now, please call me the second you see this.",
         to="cousin@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.98, true_bucket="high"),
    dict(id="T3-P-H9", subject="stove left on, house filling with smoke",
         body="I think I left the stove on, neighbor says smoke's coming from the house, can you go check right now, I'm not close by.",
         to="friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.91, true_bucket="high"),
    dict(id="T3-P-H10", subject="need you now",
         body="please call me right now, it's an emergency, i'll explain when you call",
         to="bestfriend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.85, true_bucket="high"),
    dict(id="T3-P-H11", subject="call me",
         body="call me the second you see this, something's wrong with mom",
         to="caregiver-friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.94, true_bucket="high"),
    dict(id="T3-P-H12", subject="help now",
         body="need help right now, can't explain over text just call",
         to="friend@gmail.com", from_addr="me@gmail.com",
         true_category="Personal", true_priority=0.86, true_bucket="high"),

    # ── Other - low (12) ─────────────────────────────────────────────────
    dict(id="T3-O-L1", subject="Your cable provider - channel lineup update",
         body="A few channels are being renumbered next month, no action needed, your favorites list will update automatically.",
         to="subscriber@gmail.com", from_addr="notices@primeviewcable.com",
         true_category="Other", true_priority=0.14, true_bucket="low"),
    dict(id="T3-O-L2", subject="Vet reminder - your pet is due for a checkup someday soon",
         body="Just a friendly reminder your pet is due for a wellness visit sometime in the coming months, no rush to schedule yet.",
         to="petowner@gmail.com", from_addr="reminders@willowbrookvet.com",
         true_category="Other", true_priority=0.16, true_bucket="low"),
    dict(id="T3-O-L3", subject="Your homeowners policy annual summary",
         body="Here's your annual coverage summary, nothing has changed, just for your records.",
         to="policyholder@gmail.com", from_addr="documents@harborhomeinsurance.com",
         true_category="Other", true_priority=0.13, true_bucket="low"),
    dict(id="T3-O-L4", subject="Your car rental receipt",
         body="Thanks for renting with us, here's your final receipt. No action needed.",
         to="customer@gmail.com", from_addr="receipts@roadwaycarrental.com",
         true_category="Other", true_priority=0.11, true_bucket="low"),
    dict(id="T3-O-L5", subject="Your ride receipt from last night",
         body="Here's the receipt for your ride last night, thanks for riding with us.",
         to="rider@gmail.com", from_addr="receipts@hoprideapp.com",
         true_category="Other", true_priority=0.12, true_bucket="low"),
    dict(id="T3-O-L6", subject="New course added to your learning platform",
         body="A new course was just added in a topic you've browsed before, check it out whenever you're interested.",
         to="learner@gmail.com", from_addr="notify@skillbridge.com",
         true_category="Other", true_priority=0.15, true_bucket="low"),
    dict(id="T3-O-L7", subject="Gym class you liked is coming back",
         body="The class you took a few times is back on the schedule next month, no action needed, just thought you'd want to know.",
         to="member@ironoakgym.com", from_addr="frontdesk@ironoakgym.com",
         true_category="Other", true_priority=0.14, true_bucket="low"),
    dict(id="T3-O-L8", subject="Your flight was smooth, thanks for flying",
         body="Thanks for flying with us, hope you had a good trip. No action needed on your end.",
         to="traveler@gmail.com", from_addr="feedback@skywingair.com",
         true_category="Other", true_priority=0.13, true_bucket="low"),
    dict(id="T3-O-L9", subject="Daycare waitlist - still on the list",
         body="Just confirming you're still on our waitlist, no changes needed, we'll reach out when a spot opens.",
         to="parent@gmail.com", from_addr="admissions@sunnysidedaycare.com",
         true_category="Other", true_priority=0.16, true_bucket="low"),
    dict(id="T3-O-L10", subject="Local newspaper - this week's digital edition",
         body="This week's digital edition is ready to read whenever you have time, covers the usual local news roundup.",
         to="subscriber@gmail.com", from_addr="edition@fernwoodgazette.com",
         true_category="Other", true_priority=0.12, true_bucket="low"),
    dict(id="T3-O-L11", subject="Thank you for your blood donation",
         body="Thanks so much for donating last week, your donation is on its way to help someone. No action needed.",
         to="donor@gmail.com", from_addr="thanks@lifebloodcenter.org",
         true_category="Other", true_priority=0.14, true_bucket="low"),
    dict(id="T3-O-L12", subject="your account statement is ready to view",
         body="your quarterly retirement account statement is ready online whenever you want to look, nothing needs your attention",
         to="member@meadowlarkcu.org", from_addr="statements@meadowlark401k.com",
         true_category="Other", true_priority=0.13, true_bucket="low"),

    # ── Other - medium (11) ──────────────────────────────────────────────
    dict(id="T3-O-M1", subject="Please select your channel package by next billing cycle",
         body="Your promotional package rate is ending, please choose a plan before the next billing cycle to avoid the standard rate.",
         to="subscriber@gmail.com", from_addr="billing@primeviewcable.com",
         true_category="Other", true_priority=0.39, true_bucket="medium"),
    dict(id="T3-O-M2", subject="Please schedule your pet's overdue vaccination",
         body="Your pet's vaccination is now overdue, please schedule an appointment within the next couple weeks.",
         to="petowner@gmail.com", from_addr="reminders@willowbrookvet.com",
         true_category="Other", true_priority=0.41, true_bucket="medium"),
    dict(id="T3-O-M3", subject="Homeowners policy - inspection needed soon",
         body="We need to schedule a routine home inspection within the next month to keep your policy active.",
         to="policyholder@gmail.com", from_addr="underwriting@harborhomeinsurance.com",
         true_category="Other", true_priority=0.40, true_bucket="medium"),
    dict(id="T3-O-M4", subject="Toll charges pending on your rental",
         body="A few toll charges are pending on your recent rental, please review and confirm within the next couple weeks.",
         to="customer@gmail.com", from_addr="billing@roadwaycarrental.com",
         true_category="Other", true_priority=0.34, true_bucket="medium"),
    dict(id="T3-O-M5", subject="Please rate your recent ride",
         body="We'd appreciate a rating for your recent ride, and please flag anything that felt off so we can look into it soon.",
         to="rider@gmail.com", from_addr="support@hoprideapp.com",
         true_category="Other", true_priority=0.30, true_bucket="medium"),
    dict(id="T3-O-M6", subject="Your course access expires soon",
         body="Access to your enrolled course expires in two weeks, please finish or renew before then.",
         to="learner@gmail.com", from_addr="notify@skillbridge.com",
         true_category="Other", true_priority=0.38, true_bucket="medium"),
    dict(id="T3-O-M7", subject="Please update your gym waiver on file",
         body="Your liability waiver on file is outdated, please sign the updated version sometime this week to keep access.",
         to="member@ironoakgym.com", from_addr="frontdesk@ironoakgym.com",
         true_category="Other", true_priority=0.36, true_bucket="medium"),
    dict(id="T3-O-M8", subject="Please confirm your seat selection soon",
         body="Seat selection for your upcoming flight closes in a few days, please confirm your choice before then.",
         to="traveler@gmail.com", from_addr="itinerary@skywingair.com",
         true_category="Other", true_priority=0.37, true_bucket="medium"),
    dict(id="T3-O-M9", subject="A spot opened up, please respond soon",
         body="A daycare spot just opened up for your child, please respond within 3 days to hold it or it goes to the next family.",
         to="parent@gmail.com", from_addr="admissions@sunnysidedaycare.com",
         true_category="Other", true_priority=0.45, true_bucket="medium"),
    dict(id="T3-O-M10", subject="Please renew your newspaper subscription",
         body="Your subscription lapses at the end of the month, please renew soon to avoid a gap in delivery.",
         to="subscriber@gmail.com", from_addr="billing@fernwoodgazette.com",
         true_category="Other", true_priority=0.33, true_bucket="medium"),
    dict(id="T3-O-M11", subject="please confirm your next donation slot",
         body="you're eligible to donate again soon, please confirm a time this week or next so we can keep supply steady",
         to="donor@gmail.com", from_addr="scheduling@lifebloodcenter.org",
         true_category="Other", true_priority=0.32, true_bucket="medium"),

    # ── Other - high (9) ─────────────────────────────────────────────────
    dict(id="T3-O-H1", subject="Service outage affecting emergency-line-capable phones",
         body="Your home phone service, including 911 access, is down right now due to an outage. If you have an emergency, use a cell phone or go to a neighbor immediately.",
         to="subscriber@gmail.com", from_addr="alerts@primeviewcable.com",
         true_category="Other", true_priority=0.90, true_bucket="high"),
    dict(id="T3-O-H2", subject="Your pet needs to be seen immediately",
         body="Based on the symptoms you described, please bring your pet in immediately, this cannot wait until a routine appointment.",
         to="petowner@gmail.com", from_addr="clinic@willowbrookvet.com",
         true_category="Other", true_priority=0.94, true_bucket="high"),
    dict(id="T3-O-H3", subject="Your home insurance claim needs urgent action",
         body="Storm damage to your roof is worsening, please authorize emergency repairs today to prevent further damage.",
         to="policyholder@gmail.com", from_addr="claims@harborhomeinsurance.com",
         true_category="Other", true_priority=0.83, true_bucket="high"),
    dict(id="T3-O-H4", subject="Rental car reported stolen from your location",
         body="Our tracking shows unusual activity suggesting the rental may have been stolen, please call us immediately.",
         to="customer@gmail.com", from_addr="security@roadwaycarrental.com",
         true_category="Other", true_priority=0.80, true_bucket="high"),
    dict(id="T3-O-H5", subject="Driver reports an emergency during your ride",
         body="Your driver has reported an emergency situation, please check your phone and call us immediately for an update.",
         to="rider@gmail.com", from_addr="safety@hoprideapp.com",
         true_category="Other", true_priority=0.88, true_bucket="high"),
    dict(id="T3-O-H6", subject="Certification exam window closes tonight",
         body="Your certification exam window closes at midnight tonight, please complete it now or you'll need to re-enroll.",
         to="learner@gmail.com", from_addr="notify@skillbridge.com",
         true_category="Other", true_priority=0.76, true_bucket="high"),
    dict(id="T3-O-H7", subject="Immediate evacuation ordered near the gym",
         body="A gas main break was reported near our location, please evacuate the building immediately if you're currently here.",
         to="member@ironoakgym.com", from_addr="alerts@ironoakgym.com",
         true_category="Other", true_priority=0.97, true_bucket="high"),
    dict(id="T3-O-H8", subject="flight departing early, get to the gate now",
         body="your flight is now departing 40 minutes early due to weather, please proceed to the gate immediately, final boarding is in progress",
         to="traveler@gmail.com", from_addr="alerts@skywingair.com",
         true_category="Other", true_priority=0.85, true_bucket="high"),
    dict(id="T3-O-H9", subject="urgent - your child's daycare is being evacuated",
         body="the daycare is being evacuated right now due to a fire alarm, please come to the pickup location immediately",
         to="parent@gmail.com", from_addr="admissions@sunnysidedaycare.com",
         true_category="Other", true_priority=0.99, true_bucket="high"),
]

assert len(ROWS) == 100, f"expected 100, got {len(ROWS)}"
