"""personalization

Revision ID: 1659a3790d37
Revises: 9998faba2afb
Create Date: 2026-09-29 15:48:30.118601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1659a3790d37'
down_revision: Union[str, Sequence[str], None] = '9998faba2afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalized_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.Enum('spam', 'category', 'priority', 'priority_regressor', name='personalized_model_kind'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'rejected', 'superseded', name='personalized_model_status'), nullable=False),
    sa.Column('onnx', sa.LargeBinary(), nullable=True),
    sa.Column('classes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correction_count', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'model', 'version', name='uq_personalized_models_version')
    )
    op.add_column('corrections', sa.Column('provider_message_id', sa.String(), nullable=False))
    op.create_unique_constraint('uq_corrections_message_model', 'corrections', ['email_connection_id', 'provider_message_id', 'model'])
    op.add_column('users', sa.Column('personalization_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'personalization_enabled')
    op.drop_constraint('uq_corrections_message_model', 'corrections', type_='unique')
    op.drop_column('corrections', 'provider_message_id')
    op.drop_table('personalized_models')
    # ### end Alembic commands ###
    # drop_table leaves the enum types behind; a later upgrade would then
    # fail with "type already exists".
    sa.Enum(name='personalized_model_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='personalized_model_kind').drop(op.get_bind(), checkfirst=True)
