"""add users, sessions, email_connections, corrections, classification_events, interaction_events

Revision ID: 9998faba2afb
Revises: 
Create Date: 2026-09-28 16:54:32.544007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9998faba2afb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('gmail', 'outlook', name='email_provider'), nullable=False),
    sa.Column('provider_account_id', sa.String(), nullable=False),
    sa.Column('provider_email', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('remember_me', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_connection_id', sa.UUID(), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=False),
    sa.Column('category_label', sa.String(), nullable=False),
    sa.Column('priority_bucket', sa.String(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('spam_label', sa.String(), nullable=False),
    sa.Column('sentiment_compound', sa.Float(), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_connection_id'], ['email_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_connection_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.Enum('category', 'priority', 'spam', name='correction_model'), nullable=False),
    sa.Column('feature_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('predicted_label', sa.String(), nullable=False),
    sa.Column('predicted_confidence', sa.Float(), nullable=False),
    sa.Column('corrected_label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_connection_id'], ['email_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_connection_id', sa.UUID(), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('opened', 'archived', 'replied', 'flagged', name='interaction_action'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_connection_id'], ['email_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interaction_events')
    op.drop_table('corrections')
    op.drop_table('classification_events')
    op.drop_table('sessions')
    op.drop_table('email_connections')
    op.drop_table('users')
    # ### end Alembic commands ###
